Bstruct bstruct_create(const char *);
Bstruct bstruct_open(const char *,Bool);
Bstruct bstruct_append(const char *,Bool);
int bstruct_getmiss(const Bstruct);
FILE *bstruct_getfile(Bstruct);
Hash bstruct_gethash(Bstruct);
void bstruct_freehash(Bstruct);
Bool bstruct_isdefined(Bstruct,const char *);
Bool bstruct_writearrayindex(Bstruct,long long,long long vec[],int,int);
void bstruct_close(Bstruct);
void bstruct_sync(Bstruct);
void bstruct_setout(Bstruct,Bool);
Bool bstruct_writebool(Bstruct,const char *,Bool);
Bool bstruct_writebyte(Bstruct,const char *,Byte);
Bool bstruct_writeint(Bstruct,const char *,int);
Bool bstruct_writeshort(Bstruct,const char *,short);
Bool bstruct_writeushort(Bstruct,const char *,unsigned short);
Bool bstruct_writeintarray(Bstruct,const char *,const int[],int);
Bool bstruct_writeshortarray(Bstruct,const char *,const short[],int);
Bool bstruct_writeushortarray(Bstruct,const char *,const unsigned short[],int);
Bool bstruct_writereal(Bstruct,const char *,Real);
Bool bstruct_writefloat(Bstruct,const char *,float);
Bool bstruct_writerealarray(Bstruct,const char *,const Real [],int);
Bool bstruct_writestring(Bstruct,const char *,const char *);
Bool bstruct_writearray(Bstruct,const char *,int);
Bool bstruct_writeindexarray(Bstruct,const char *,long long *,int);
Bool bstruct_writestruct(Bstruct,const char *);
Bool bstruct_writeendstruct(Bstruct);
Bool bstruct_writeendarray(Bstruct);
void bstruct_fprintdata(FILE *,const Bstruct_data *);
Bool bstruct_readdata(Bstruct,Bstruct_data *);
void bstruct_freedata(Bstruct_data *);
Bool bstruct_readarray(Bstruct,const char *,int *);
Bool bstruct_readindexarray(Bstruct,long long *,int);
Bool bstruct_seekindexarray(Bstruct,int,int);
Bool bstruct_readbool(Bstruct,const char *,Bool *);
Bool bstruct_readbyte(Bstruct,const char *,Byte *);
Bool bstruct_readint(Bstruct,const char *,int *);
Bool bstruct_readintarray(Bstruct,const char *,int *,int);
Bool bstruct_readshort(Bstruct,const char *,short *);
Bool bstruct_readushort(Bstruct,const char *,unsigned short *);
Bool bstruct_readfloat(Bstruct,const char *,float *);
Bool bstruct_readreal(Bstruct,const char *,Real *);
Bool bstruct_readstruct(Bstruct,const char *);
char *bstruct_readstring(Bstruct,const char *);
Bool bstruct_readendstruct(Bstruct,const char *);
Bool bstruct_readendarray(Bstruct,const char *);
Bool bstruct_readushortarray(Bstruct,const char *,unsigned short[],int);
Bool bstruct_readshortarray(Bstruct,const char *,short[],int);
Bool bstruct_readrealarray(Bstruct,const char *,Real [],int);
Real *bstruct_readvarrealarray(Bstruct,const char *,int *);
long long bstruct_getarrayindex(Bstruct);
