/**************************************************************************************/
/**                                                                                \n**/
/**                      m a n a g e _ i r r i g . j s                             \n**/
/**                                                                                \n**/
/**     management parameter data                                                  \n**/
/**                                                                                \n**/
/** (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file    \n**/
/** authors, and contributors see AUTHORS file                                     \n**/
/** This file is part of LPJmL and licensed under GNU AGPL Version 3               \n**/
/** or later. See LICENSE file or go to http://www.gnu.org/licenses/               \n**/
/** Contact: https://github.com/PIK-LPJmL/LPJmL                                    \n**/
/**                                                                                \n**/
/**************************************************************************************/

#include "../include/managepar.h"

"countrypar" :
[
  { "id" : Afghanistan, "name" : "Afghanistan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Aland_Islands, "name" :  "Aland Islands", "laimax_tempcer" : 3, "laimax_maize" :	6, "default_irrig_system" :	2},
  { "id" : Albania, "name" : "Albania", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Algeria, "name" : "Algeria", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : American_Samoa, "name" : "American Samoa", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Angola, "name" : "Angola", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Anguilla, "name" :  "Anguilla", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Antigua_and_Barbuda, "name" :  "Antigua and Barbuda", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Argentina, "name" : "Argentina", "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Armenia, "name" : "Armenia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Austria, "name" : "Austria", "laimax_tempcer" : 5, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Azerbaijan, "name" : "Azerbaijan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bahamas_The, "name" : "Bahamas, The", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Bahrain, "name" :  "Bahrain", "laimax_tempcer" : 6, "laimax_maize" :	6, "default_irrig_system" :	2},
  { "id" : Bangladesh, "name" : "Bangladesh", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Barbados, "name" :  "Barbados", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Belgium, "name" : "Belgium", "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Belize, "name" : "Belize", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Benin, "name" : "Benin", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Bermuda, "name" :  "Bermuda", "laimax_tempcer" : 7, "laimax_maize" :	4, "default_irrig_system" :	2},
  { "id" : Bhutan, "name" : "Bhutan", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bolivia, "name" : "Bolivia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bosnia_and_Herzegovina, "name" : "Bosnia and Herzegovina", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Botswana, "name" : "Botswana", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : British_Indian_Ocean_Territory, "name" :  "British Indian Ocean Territory", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Brunei, "name" : "Brunei", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Bulgaria, "name" : "Bulgaria", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Burkina_Faso, "name" : "Burkina Faso", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Burundi, "name" : "Burundi", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Byelarus, "name" : "Byelarus", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Cambodia, "name" : "Cambodia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cameroon, "name" : "Cameroon", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cape_Verde, "name" : "Cape Verde", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Cayman_Islands, "name" : "Cayman Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Central_African_Republic, "name" : "Central African Republic", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Chad, "name" : "Chad", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Chile, "name" : "Chile", "laimax_tempcer" : 5, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Christmas_Island, "name" :  "Christmas Island", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Cocos_Keeling_Islands, "name" :  "Cocos Keeling Islands", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Colombia, "name" : "Colombia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Comoros, "name" : "Comoros", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Congo_Brazzaville, "name" : "Congo-Brazzaville", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cook_Islands, "name" : "Cook Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Costa_Rica, "name" : "Costa Rica", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Croatia, "name" : "Croatia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Cuba, "name" : "Cuba", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Curacao, "name" :  "Curacao", "laimax_tempcer" : 4, "laimax_maize" :	6, "default_irrig_system" :	1},
  { "id" : Cyprus, "name" : "Cyprus", "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 3},
  { "id" : Czech_Republic, "name" : "Czech Republic", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Denmark, "name" : "Denmark", "laimax_tempcer" : 7, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Djibouti, "name" : "Djibouti", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Dominica, "name" :  "Dominica", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Dominican_Republic, "name" : "Dominican Republic", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Ecuador, "name" : "Ecuador", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Egypt, "name" : "Egypt", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : El_Salvador, "name" : "El Salvador", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Equatorial_Guinea, "name" : "Equatorial Guinea", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Eritrea, "name" : "Eritrea", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Estonia, "name" : "Estonia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Ethiopia, "name" : "Ethiopia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Falkland_Islands_or_Islas_Malvinas, "name" : "Falkland Islands (Islas Malvinas)", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Faroe_Islands, "name" : "Faroe Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Federated_States_of_Micronesia, "name" : "Federated States of Micronesia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Fiji, "name" : "Fiji", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Finland, "name" : "Finland", "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : France, "name" : "France", "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : French_Guiana, "name" : "French Guiana", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : French_Polynesia, "name" : "French Polynesia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : French_Southern_and_Antarctica_Lands, "name" : "French Southern and Antarctica Lands", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Gabon, "name" : "Gabon", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Gambia_The, "name" : "Gambia, The", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Georgia, "name" : "Georgia", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Germany, "name" : "Germany", "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Ghana, "name" : "Ghana", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Greece, "name" : "Greece", "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Greenland, "name" : "Greenland", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Grenada, "name" :  "Grenada", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Guadeloupe, "name" : "Guadeloupe", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Guam, "name" :  "Guam", "laimax_tempcer" :	4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Guatemala, "name" : "Guatemala", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guernsey, "name" :  "Guernsey", "laimax_tempcer" :	7, "laimax_maize" :	7, "default_irrig_system" :	2},
  { "id" : Guinea_Bissau, "name" : "Guinea-Bissau", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guinea, "name" : "Guinea", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guyana, "name" : "Guyana", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Haiti, "name" : "Haiti", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Heard_Island_and_McDonald_Islands, "name" :  "Heard Island and McDonald Islands", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Honduras, "name" : "Honduras", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Hong_Kong, "name" :  "Hong Kong", "laimax_tempcer" : 6, "laimax_maize" :	7, "default_irrig_system" :	1},
  { "id" : Hungary, "name" : "Hungary", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Iceland, "name" : "Iceland", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Indonesia, "name" : "Indonesia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Iran, "name" : "Iran", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Iraq, "name" : "Iraq", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Ireland, "name" : "Ireland", "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Isle_of_Man, "name" :  "Isle of Man", "laimax_tempcer" : 7, "laimax_maize" :	4, "default_irrig_system" :	2},
  { "id" : Israel, "name" : "Israel", "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Italy, "name" : "Italy", "laimax_tempcer" : 4, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Ivory_Coast, "name" : "Ivory Coast", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Jamaica, "name" : "Jamaica", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Japan, "name" : "Japan", "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : Jersey, "name" :  "Jersey", "laimax_tempcer" : 7, "laimax_maize" :	7, "default_irrig_system" :	2},
  { "id" : Jordan, "name" : "Jordan", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Kazakhstan, "name" : "Kazakhstan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Kenya, "name" : "Kenya", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Kiribati, "name" : "Kiribati", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Kosovo, "name" :  "Kosovo", "laimax_tempcer" : 3, "laimax_maize" :	5, "default_irrig_system" :	1},
  { "id" : Kuwait, "name" : "Kuwait", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Kyrgyzstan, "name" : "Kyrgyzstan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Laos, "name" : "Laos", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Latvia, "name" : "Latvia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lebanon, "name" : "Lebanon", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lesotho, "name" : "Lesotho", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Liberia, "name" : "Liberia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Libya, "name" : "Libya", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lithuania, "name" : "Lithuania", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Luxembourg, "name" : "Luxembourg", "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Macedonia, "name" : "Macedonia", "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Madagascar, "name" : "Madagascar", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Malawi, "name" : "Malawi", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Malaysia, "name" : "Malaysia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Maldives, "name" : "Maldives", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mali, "name" : "Mali", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Malta, "name" :  "Malta", "laimax_tempcer" : 4, "laimax_maize" :	7, "default_irrig_system" :	2},
  { "id" : Marshall_Islands, "name" : "Marshall Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Martinique, "name" :  "Martinique", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Mauritania, "name" : "Mauritania", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mauritius, "name" : "Mauritius", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mayotte, "name" :  "Mayotte", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Mexico, "name" : "Mexico", "laimax_tempcer" : 5, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Moldova, "name" : "Moldova", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mongolia, "name" : "Mongolia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Montenegro, "name" : "Montenegro", "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Montserrat, "name" :  "Montserrat", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Morocco, "name" : "Morocco", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mozambique, "name" : "Mozambique", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Myanmar_or_Burma, "name" : "Myanmar (Burma)", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Namibia, "name" : "Namibia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Nauru, "name" :  "Nauru", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Nepal, "name" : "Nepal", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Netherlands, "name" : "Netherlands", "laimax_tempcer" : 7, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : New_Caledonia, "name" : "New Caledonia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : New_Zealand, "name" : "New Zealand", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Nicaragua, "name" : "Nicaragua", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Niger, "name" : "Niger", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Nigeria, "name" : "Nigeria", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Niue, "name" :  "Niue", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : No_Land, "name" :  "No Land", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Norfolk_Island, "name" :  "Norfolk Island", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : North_Korea, "name" : "North Korea", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Northern_Mariana_Islands, "name" : "Northern Mariana Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Norway, "name" : "Norway", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Oman, "name" : "Oman", "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Pakistan, "name" : "Pakistan", "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Palau, "name" :  "Palau", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Panama, "name" : "Panama", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Papua_New_Guinea, "name" : "Papua New Guinea", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Paraguay, "name" : "Paraguay", "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Peru, "name" : "Peru", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Philippines, "name" : "Philippines", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Pitcairn_Islands, "name" : "Pitcairn Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Poland, "name" : "Poland", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Portugal, "name" : "Portugal", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Puerto_Rico, "name" : "Puerto Rico", "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Qatar, "name" : "Qatar", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Reunion, "name" : "Reunion", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Romania, "name" : "Romania", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Rwanda, "name" : "Rwanda", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Saint_Helena_Ascension_and_Tristan_da_Cunha, "name" :  "Saint Helena Ascension and Tristan da Cunha", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Saint_Kitts_and_Nevis, "name" :  "Saint Kitts and Nevis", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Saint_Lucia, "name" :  "Saint Lucia", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Saint_Pierre_and_Miquelon, "name" :  "Saint Pierre and Miquelon", "laimax_tempcer" : 3, "laimax_maize" :	7, "default_irrig_system" :	2},
  { "id" : Sao_Tome_and_Principe, "name" : "Sao Tome and Principe", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Saudi_Arabia, "name" : "Saudi Arabia", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Senegal, "name" : "Senegal", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Serbia, "name" : "Serbia", "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Seychelles, "name" :  "Seychelles", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Sierra_Leone, "name" : "Sierra Leone", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Singapore, "name" :  "Singapore", "laimax_tempcer" : 3, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Slovakia, "name" : "Slovakia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Slovenia, "name" : "Slovenia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Solomon_Islands, "name" : "Solomon Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Somalia, "name" : "Somalia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : South_Africa, "name" : "South Africa", "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : South_Georgia_and_the_South_Sandwich_Islands, "name" : "South Georgia and the South Sandwich Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : South_Korea, "name" : "South Korea", "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : South_Sudan, "name" :  "South Sudan", "laimax_tempcer" : 3, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Spain, "name" : "Spain", "laimax_tempcer" : 4.5, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Sri_Lanka, "name" : "Sri Lanka", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : St_Vincent_and_the_Grenadines, "name" : "St. Vincent and the Grenadines", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Sudan, "name" : "Sudan", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Suriname, "name" : "Suriname", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Svalbard, "name" : "Svalbard", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Swaziland, "name" : "Swaziland", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Sweden, "name" : "Sweden", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Switzerland, "name" : "Switzerland", "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Syria, "name" : "Syria", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Taiwan, "name" : "Taiwan", "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Tajikistan, "name" : "Tajikistan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tanzania_United_Republic_of, "name" : "Tanzania, United Republic of", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Thailand, "name" : "Thailand", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Timor_Leste, "name" :  "Timor Leste", "laimax_tempcer" : 3, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Togo, "name" : "Togo", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tokelau, "name" : "Tokelau", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Tonga, "name" :  "Tonga", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : Trinidad_and_Tobago, "name" : "Trinidad and Tobago", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tunisia, "name" : "Tunisia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Turkey, "name" : "Turkey", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Turkmenistan, "name" : "Turkmenistan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Turks_and_Caicos_Islands, "name" :  "Turks and Caicos Islands", "laimax_tempcer" : 4, "laimax_maize" :	5, "default_irrig_system" :	2},
  { "id" : Tuvalu, "name" : "Tuvalu", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Uganda, "name" : "Uganda", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Ukraine, "name" : "Ukraine", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_Arab_Emirates, "name" : "United Arab Emirates", "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 3},
  { "id" : United_Kingdom, "name" : "United Kingdom", "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_States_Minor_Outlying_Islands, "name" :  "United States Minor Outlying Islands", "laimax_tempcer" : 3, "laimax_maize" :	7, "default_irrig_system" :	2},
  { "id" : Uruguay, "name" : "Uruguay", "laimax_tempcer" : 5, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Uzbekistan, "name" : "Uzbekistan", "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Vanuatu, "name" : "Vanuatu", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Venezuela, "name" : "Venezuela", "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Vietnam, "name" : "Vietnam", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Virgin_Islands, "name" : "Virgin Islands", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Wallis_and_Futuna, "name" :  "Wallis and Futuna", "laimax_tempcer" : 2, "laimax_maize" :	4, "default_irrig_system" :	1},
  { "id" : West_Bank, "name" : "West Bank", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Western_Sahara, "name" : "Western Sahara", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Western_Samoa, "name" : "Western Samoa", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Yemen, "name" : "Yemen", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Zaire_DR_Congo, "name" : "DR Congo, former Zaire", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Zambia, "name" : "Zambia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Zimbabwe, "name" : "Zimbabwe", "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Australia, "name" : "Australia", "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Brazil, "name" : "Brazil", "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Canada, "name" : "Canada", "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : China, "name" : "China", "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : India, "name" : "India", "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Russia, "name" : "Russia", "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_States, "name" : "United States", "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2}
],
