/**************************************************************************************/
/**                                                                                \n**/
/**  manage_laimax_alphaa_fao.rev.4453.js    \n**/
/**                                                                                \n**/
/**     management parameter data with maximum LAI values for all crops            \n**/
/**               LPJmL Version 4.0.002                                            \n**/
/**                                                                                \n**/
/** (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file    \n**/
/** authors, and contributors see AUTHORS file                                     \n**/
/** This file is part of LPJmL and licensed under GNU AGPL Version 3               \n**/
/** or later. See LICENSE file or go to http://www.gnu.org/licenses/               \n**/
/** Contact: https://github.com/PIK-LPJmL/LPJmL                                    \n**/
/**                                                                                \n**/
/**************************************************************************************/

#include "../include/managepar.h"

"countrypar" :
[
  { "id" : Afghanistan, "name" : "Afghanistan", "laimax" : [ 1, 5, 2, 1, 2, 1, 6, 3, 7, 2, 3, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Aland_Islands, "name" : "Aland Islands", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Albania, "name" : "Albania", "laimax" : [ 2, 6, 3, 4, 5, 2, 1, 3, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Algeria, "name" : "Algeria", "laimax" : [ 1, 6, 3, 5, 1, 6, 1, 1, 7, 4, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : American_Samoa, "name" : "American Samoa", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Angola, "name" : "Angola", "laimax" : [ 2, 1, 1, 1, 1, 1, 4, 4, 3, 1, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Anguilla, "name" : "Anguilla", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Antigua_and_Barbuda, "name" : "Antigua and Barbuda", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Argentina, "name" : "Argentina", "laimax" : [ 1, 4, 5, 3, 1, 5, 2, 4, 5, 2, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Armenia, "name" : "Armenia", "laimax" : [ 2, 3, 7, 5, 2, 1, 1, 2, 2, 1, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Austria, "name" : "Austria", "laimax" : [ 4, 6, 7, 7, 2, 6, 1, 4, 6, 5, 4, 1], "laimax_tempcer" : 5, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Azerbaijan, "name" : "Azerbaijan", "laimax" : [ 2, 3, 3, 5, 2, 3, 1, 4, 2, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bahamas_The, "name" : "Bahamas The", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Bahrain, "name" : "Bahrain", "laimax" : [ 2, 6, 5, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Bangladesh, "name" : "Bangladesh", "laimax" : [ 4, 5, 4, 2, 2, 1, 6, 2, 7, 3, 2, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Barbados, "name" : "Barbados", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Belgium, "name" : "Belgium", "laimax" : [ 4, 6, 7, 4, 3, 6, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Belize, "name" : "Belize", "laimax" : [ 1, 4, 2, 2, 2, 5, 4, 4, 5, 2, 7, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Benin, "name" : "Benin", "laimax" : [ 2, 3, 1, 2, 1, 1, 4, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Bermuda, "name" : "Bermuda", "laimax" : [ 2, 5, 7, 4, 3, 7, 1, 7, 4, 4, 4, 7], "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Bhutan, "name" : "Bhutan", "laimax" : [ 1, 4, 2, 2, 2, 1, 6, 2, 5, 2, 3, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bolivia, "name" : "Bolivia", "laimax" : [ 1, 3, 3, 2, 2, 5, 3, 3, 7, 2, 7, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Bosnia_and_Herzegovina, "name" : "Bosnia and Herzegovina", "laimax" : [ 2, 6, 4, 4, 2, 1, 1, 1, 3, 5, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Botswana, "name" : "Botswana", "laimax" : [ 3, 2, 1, 1, 1, 1, 3, 4, 3, 2, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : British_Indian_Ocean_Territory, "name" : "British Indian Ocean Territory", "laimax" : [ 4, 4, 2, 3, 2, 1, 6, 2, 7, 2, 3, 4], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Brunei, "name" : "Brunei", "laimax" : [ 2, 1, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Bulgaria, "name" : "Bulgaria", "laimax" : [ 2, 5, 5, 3, 3, 2, 1, 4, 2, 7, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Burkina_Faso, "name" : "Burkina Faso", "laimax" : [ 2, 2, 2, 2, 1, 1, 1, 4, 3, 1, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Burundi, "name" : "Burundi", "laimax" : [ 1, 2, 1, 2, 1, 1, 3, 4, 1, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Byelarus, "name" : "Byelarus", "laimax" : [ 2, 3, 3, 5, 2, 4, 1, 4, 2, 1, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Cambodia, "name" : "Cambodia", "laimax" : [ 3, 3, 3, 5, 2, 6, 5, 7, 5, 2, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cameroon, "name" : "Cameroon", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 1, 1, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cape_Verde, "name" : "Cape Verde", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Cayman_Islands, "name" : "Cayman Islands", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Central_African_Republic, "name" : "Central African Republic", "laimax" : [ 2, 2, 1, 2, 1, 1, 1, 4, 3, 1, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Chad, "name" : "Chad", "laimax" : [ 2, 1, 1, 1, 1, 1, 3, 4, 3, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Chile, "name" : "Chile", "laimax" : [ 2, 7, 7, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 5, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Christmas_Island, "name" : "Christmas Island", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cocos_Keeling_Islands, "name" : "Cocos Keeling Islands", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Colombia, "name" : "Colombia", "laimax" : [ 1, 5, 3, 2, 2, 5, 3, 4, 6, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Comoros, "name" : "Comoros", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Congo_Brazzaville, "name" : "Congo Brazzaville", "laimax" : [ 2, 1, 1, 2, 1, 1, 2, 4, 3, 1, 1, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Cook_Islands, "name" : "Cook Islands", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Costa_Rica, "name" : "Costa Rica", "laimax" : [ 1, 4, 2, 2, 2, 5, 4, 4, 5, 2, 7, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Croatia, "name" : "Croatia", "laimax" : [ 3, 6, 4, 6, 2, 5, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Cuba, "name" : "Cuba", "laimax" : [ 1, 4, 2, 2, 2, 5, 2, 4, 5, 2, 7, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Curacao, "name" : "Curacao", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Cyprus, "name" : "Cyprus", "laimax" : [ 1, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 3},
  { "id" : Czech_Republic, "name" : "Czech Republic", "laimax" : [ 3, 6, 7, 6, 2, 6, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Denmark, "name" : "Denmark", "laimax" : [ 5, 6, 5, 4, 3, 7, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 7, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Djibouti, "name" : "Djibouti", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Dominica, "name" : "Dominica", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Dominican_Republic, "name" : "Dominican Republic", "laimax" : [ 1, 3, 1, 2, 2, 5, 2, 4, 5, 1, 7, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Ecuador, "name" : "Ecuador", "laimax" : [ 1, 5, 2, 2, 2, 5, 2, 4, 6, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Egypt, "name" : "Egypt", "laimax" : [ 3, 7, 7, 5, 1, 3, 1, 6, 4, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : El_Salvador, "name" : "El Salvador", "laimax" : [ 1, 5, 2, 2, 2, 5, 3, 4, 5, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Equatorial_Guinea, "name" : "Equatorial Guinea", "laimax" : [ 2, 2, 2, 2, 1, 1, 1, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Eritrea, "name" : "Eritrea", "laimax" : [ 1, 2, 1, 1, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Estonia, "name" : "Estonia", "laimax" : [ 2, 6, 5, 4, 1, 6, 1, 4, 3, 5, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Ethiopia, "name" : "Ethiopia", "laimax" : [ 1, 2, 3, 2, 1, 1, 3, 4, 3, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Falkland_Islands_or_Islas_Malvinas, "name" : "Falkland Islands or Islas Malvinas", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Faroe_Islands, "name" : "Faroe Islands", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Federated_States_of_Micronesia, "name" : "Federated States of Micronesia", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Fiji, "name" : "Fiji", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Finland, "name" : "Finland", "laimax" : [ 3, 6, 5, 4, 2, 7, 1, 4, 3, 5, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : France, "name" : "France", "laimax" : [ 4, 5, 7, 7, 4, 7, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : French_Guiana, "name" : "French Guiana", "laimax" : [ 1, 3, 3, 2, 2, 5, 2, 4, 5, 2, 7, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : French_Polynesia, "name" : "French Polynesia", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : French_Southern_and_Antarctica_Lands, "name" : "French Southern and Antarctica Lands", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Gabon, "name" : "Gabon", "laimax" : [ 2, 3, 2, 2, 1, 1, 1, 4, 3, 2, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Gambia_The, "name" : "Gambia The", "laimax" : [ 2, 2, 1, 2, 1, 1, 1, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Georgia, "name" : "Georgia", "laimax" : [ 1, 3, 3, 5, 1, 3, 1, 1, 7, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Germany, "name" : "Germany", "laimax" : [ 5, 6, 7, 4, 3, 6, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Ghana, "name" : "Ghana", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 2, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Greece, "name" : "Greece", "laimax" : [ 1, 6, 7, 4, 3, 5, 1, 3, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Greenland, "name" : "Greenland", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Grenada, "name" : "Grenada", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Guadeloupe, "name" : "Guadeloupe", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Guam, "name" : "Guam", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Guatemala, "name" : "Guatemala", "laimax" : [ 2, 2, 2, 2, 2, 5, 1, 4, 5, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guernsey, "name" : "Guernsey", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Guinea, "name" : "Guinea", "laimax" : [ 2, 2, 1, 2, 1, 1, 2, 4, 3, 2, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guinea_Bissau, "name" : "Guinea Bissau", "laimax" : [ 2, 2, 2, 2, 1, 1, 4, 4, 3, 2, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Guyana, "name" : "Guyana", "laimax" : [ 1, 4, 2, 2, 2, 5, 3, 4, 5, 1, 7, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Haiti, "name" : "Haiti", "laimax" : [ 1, 2, 1, 2, 2, 5, 1, 4, 5, 1, 7, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Heard_Island_and_McDonald_Islands, "name" : "Heard Island and McDonald Islands", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Honduras, "name" : "Honduras", "laimax" : [ 1, 3, 1, 2, 2, 5, 1, 4, 5, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Hong_Kong, "name" : "Hong Kong", "laimax" : [ 3, 6, 4, 5, 2, 6, 5, 7, 3, 4, 2, 6], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : Hungary, "name" : "Hungary", "laimax" : [ 3, 7, 6, 2, 2, 7, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Iceland, "name" : "Iceland", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Indonesia, "name" : "Indonesia", "laimax" : [ 2, 4, 3, 2, 1, 1, 3, 2, 3, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Iran, "name" : "Iran", "laimax" : [ 2, 7, 7, 1, 1, 7, 1, 1, 7, 6, 2, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Iraq, "name" : "Iraq", "laimax" : [ 1, 3, 2, 5, 1, 2, 1, 3, 7, 6, 2, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Ireland, "name" : "Ireland", "laimax" : [ 4, 6, 5, 4, 3, 4, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Isle_of_Man, "name" : "Isle of Man", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Israel, "name" : "Israel", "laimax" : [ 2, 6, 7, 5, 1, 6, 1, 7, 7, 7, 2, 7], "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Italy, "name" : "Italy", "laimax" : [ 2, 5, 6, 4, 4, 6, 1, 6, 5, 5, 2, 1], "laimax_tempcer" : 4, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Ivory_Coast, "name" : "Ivory Coast", "laimax" : [ 2, 2, 2, 2, 1, 1, 2, 4, 3, 1, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Jamaica, "name" : "Jamaica", "laimax" : [ 1, 4, 1, 2, 2, 5, 5, 4, 5, 2, 7, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Japan, "name" : "Japan", "laimax" : [ 2, 7, 3, 3, 2, 7, 1, 7, 3, 3, 6, 7], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : Jersey, "name" : "Jersey", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Jordan, "name" : "Jordan", "laimax" : [ 2, 6, 1, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Kazakhstan, "name" : "Kazakhstan", "laimax" : [ 1, 4, 3, 2, 2, 2, 1, 3, 7, 7, 4, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Kenya, "name" : "Kenya", "laimax" : [ 4, 3, 2, 1, 1, 1, 5, 2, 3, 2, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Kiribati, "name" : "Kiribati", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Kosovo, "name" : "Kosovo", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Kuwait, "name" : "Kuwait", "laimax" : [ 3, 6, 5, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Kyrgyzstan, "name" : "Kyrgyzstan", "laimax" : [ 2, 3, 7, 6, 1, 5, 1, 7, 2, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Laos, "name" : "Laos", "laimax" : [ 3, 4, 3, 5, 2, 6, 3, 7, 4, 2, 2, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Latvia, "name" : "Latvia", "laimax" : [ 2, 6, 5, 4, 1, 5, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lebanon, "name" : "Lebanon", "laimax" : [ 2, 6, 2, 5, 7, 4, 1, 4, 7, 7, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lesotho, "name" : "Lesotho", "laimax" : [ 1, 2, 1, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Liberia, "name" : "Liberia", "laimax" : [ 2, 2, 2, 2, 1, 1, 2, 4, 1, 1, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Libya, "name" : "Libya", "laimax" : [ 1, 6, 1, 1, 2, 6, 1, 4, 7, 5, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Lithuania, "name" : "Lithuania", "laimax" : [ 3, 6, 3, 4, 2, 6, 1, 4, 3, 5, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Luxembourg, "name" : "Luxembourg", "laimax" : [ 4, 6, 6, 4, 3, 6, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Macedonia, "name" : "Macedonia", "laimax" : [ 2, 7, 5, 4, 3, 4, 1, 3, 2, 5, 7, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Madagascar, "name" : "Madagascar", "laimax" : [ 2, 2, 1, 2, 1, 1, 1, 4, 3, 1, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Malawi, "name" : "Malawi", "laimax" : [ 1, 1, 2, 1, 1, 1, 7, 1, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Malaysia, "name" : "Malaysia", "laimax" : [ 2, 3, 3, 2, 1, 1, 2, 2, 3, 5, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Maldives, "name" : "Maldives", "laimax" : [ 4, 4, 2, 3, 2, 1, 6, 2, 7, 2, 3, 4], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mali, "name" : "Mali", "laimax" : [ 3, 4, 2, 2, 1, 1, 4, 4, 3, 1, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Malta, "name" : "Malta", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Marshall_Islands, "name" : "Marshall Islands", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Martinique, "name" : "Martinique", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mauritania, "name" : "Mauritania", "laimax" : [ 2, 5, 1, 1, 1, 1, 3, 4, 3, 7, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mauritius, "name" : "Mauritius", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mayotte, "name" : "Mayotte", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Mexico, "name" : "Mexico", "laimax" : [ 4, 4, 3, 2, 4, 5, 4, 4, 3, 2, 7, 7], "laimax_tempcer" : 5, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Moldova, "name" : "Moldova", "laimax" : [ 2, 3, 3, 1, 1, 2, 1, 2, 2, 1, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mongolia, "name" : "Mongolia", "laimax" : [ 1, 6, 4, 5, 2, 6, 5, 7, 3, 4, 2, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Montenegro, "name" : "Montenegro", "laimax" : [ 1, 6, 2, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Montserrat, "name" : "Montserrat", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Morocco, "name" : "Morocco", "laimax" : [ 1, 5, 2, 7, 1, 5, 1, 6, 7, 7, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Mozambique, "name" : "Mozambique", "laimax" : [ 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Myanmar_or_Burma, "name" : "Myanmar or Burma", "laimax" : [ 3, 5, 3, 3, 2, 1, 4, 3, 5, 3, 3, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Namibia, "name" : "Namibia", "laimax" : [ 2, 2, 3, 1, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Nauru, "name" : "Nauru", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Nepal, "name" : "Nepal", "laimax" : [ 2, 3, 2, 3, 2, 1, 6, 2, 3, 2, 3, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Netherlands, "name" : "Netherlands", "laimax" : [ 5, 6, 7, 4, 3, 7, 1, 4, 3, 5, 4, 1], "laimax_tempcer" : 7, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : New_Caledonia, "name" : "New Caledonia", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : New_Zealand, "name" : "New Zealand", "laimax" : [ 3, 7, 7, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Nicaragua, "name" : "Nicaragua", "laimax" : [ 1, 3, 1, 2, 2, 5, 2, 4, 5, 5, 7, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Niger, "name" : "Niger", "laimax" : [ 2, 4, 1, 1, 1, 1, 7, 4, 3, 1, 1, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Nigeria, "name" : "Nigeria", "laimax" : [ 2, 2, 2, 3, 1, 1, 3, 4, 3, 2, 1, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Niue, "name" : "Niue", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : No_Land, "name" : "No Land", "laimax" : [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Norfolk_Island, "name" : "Norfolk Island", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : North_Korea, "name" : "North Korea", "laimax" : [ 2, 5, 3, 7, 1, 1, 4, 2, 2, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Northern_Mariana_Islands, "name" : "Northern Mariana Islands", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Norway, "name" : "Norway", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 2, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Oman, "name" : "Oman", "laimax" : [ 2, 6, 5, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 3},
  { "id" : Pakistan, "name" : "Pakistan", "laimax" : [ 4, 4, 3, 2, 2, 1, 6, 7, 7, 7, 3, 5], "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Palau, "name" : "Palau", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Panama, "name" : "Panama", "laimax" : [ 1, 3, 2, 2, 2, 5, 4, 4, 5, 2, 7, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Papua_New_Guinea, "name" : "Papua New Guinea", "laimax" : [ 2, 4, 3, 2, 1, 1, 3, 2, 3, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Paraguay, "name" : "Paraguay", "laimax" : [ 2, 2, 2, 2, 2, 5, 3, 3, 6, 1, 7, 7], "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Peru, "name" : "Peru", "laimax" : [ 1, 7, 5, 2, 2, 5, 4, 4, 5, 2, 7, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Philippines, "name" : "Philippines", "laimax" : [ 2, 3, 2, 2, 1, 1, 2, 2, 3, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Pitcairn_Islands, "name" : "Pitcairn Islands", "laimax" : [ 2, 7, 3, 4, 2, 7, 1, 7, 4, 4, 6, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Poland, "name" : "Poland", "laimax" : [ 3, 6, 5, 7, 2, 5, 1, 2, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Portugal, "name" : "Portugal", "laimax" : [ 1, 7, 4, 4, 5, 4, 1, 1, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Puerto_Rico, "name" : "Puerto Rico", "laimax" : [ 2, 5, 7, 4, 3, 7, 1, 7, 4, 4, 4, 1], "laimax_tempcer" : 3, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Qatar, "name" : "Qatar", "laimax" : [ 2, 6, 5, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Reunion, "name" : "Reunion", "laimax" : [ 4, 4, 2, 3, 2, 1, 6, 2, 7, 2, 3, 4], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Romania, "name" : "Romania", "laimax" : [ 2, 3, 3, 3, 2, 3, 1, 3, 3, 5, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Rwanda, "name" : "Rwanda", "laimax" : [ 1, 2, 1, 1, 1, 1, 2, 4, 1, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Saint_Helena_Ascension_and_Tristan_da_Cunha, "name" : "Saint Helena Ascension and Tristan da Cunha", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Saint_Kitts_and_Nevis, "name" : "Saint Kitts and Nevis", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Saint_Lucia, "name" : "Saint Lucia", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Saint_Pierre_and_Miquelon, "name" : "Saint Pierre and Miquelon", "laimax" : [ 2, 5, 7, 4, 3, 7, 1, 7, 4, 4, 4, 7], "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Sao_Tome_and_Principe, "name" : "Sao Tome and Principe", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Saudi_Arabia, "name" : "Saudi Arabia", "laimax" : [ 7, 6, 5, 7, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Senegal, "name" : "Senegal", "laimax" : [ 2, 3, 2, 1, 1, 1, 3, 4, 3, 1, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Serbia, "name" : "Serbia", "laimax" : [ 1, 6, 2, 4, 1, 2, 1, 1, 1, 5, 1, 1], "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Seychelles, "name" : "Seychelles", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Sierra_Leone, "name" : "Sierra Leone", "laimax" : [ 2, 2, 1, 3, 1, 1, 2, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Singapore, "name" : "Singapore", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Slovakia, "name" : "Slovakia", "laimax" : [ 3, 6, 5, 5, 2, 4, 1, 3, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Slovenia, "name" : "Slovenia", "laimax" : [ 3, 6, 6, 2, 2, 3, 1, 2, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Solomon_Islands, "name" : "Solomon Islands", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Somalia, "name" : "Somalia", "laimax" : [ 2, 5, 1, 2, 1, 1, 4, 4, 3, 1, 1, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : South_Africa, "name" : "South Africa", "laimax" : [ 4, 2, 3, 1, 1, 1, 3, 5, 6, 3, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : South_Georgia_and_the_South_Sandwich_Islands, "name" : "South Georgia and the South Sandwich Islands", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : South_Korea, "name" : "South Korea", "laimax" : [ 2, 5, 3, 2, 1, 1, 4, 2, 2, 4, 1, 3], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : South_Sudan, "name" : "South Sudan", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Spain, "name" : "Spain", "laimax" : [ 2, 7, 7, 1, 7, 6, 1, 6, 3, 5, 2, 1], "laimax_tempcer" : 4.5, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Sri_Lanka, "name" : "Sri Lanka", "laimax" : [ 4, 4, 2, 2, 2, 1, 2, 2, 7, 1, 3, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : St_Vincent_and_the_Grenadines, "name" : "St Vincent and the Grenadines", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Sudan, "name" : "Sudan", "laimax" : [ 3, 2, 1, 1, 1, 1, 3, 2, 3, 1, 1, 4], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Suriname, "name" : "Suriname", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Svalbard, "name" : "Svalbard", "laimax" : [ 3, 6, 5, 4, 5, 6, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Swaziland, "name" : "Swaziland", "laimax" : [ 2, 2, 1, 2, 1, 1, 3, 4, 3, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Sweden, "name" : "Sweden", "laimax" : [ 4, 6, 5, 4, 2, 7, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 2},
  { "id" : Switzerland, "name" : "Switzerland", "laimax" : [ 4, 6, 7, 4, 3, 7, 1, 6, 7, 5, 4, 1], "laimax_tempcer" : 7, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Syria, "name" : "Syria", "laimax" : [ 2, 6, 3, 1, 7, 7, 1, 2, 7, 5, 2, 7], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Taiwan, "name" : "Taiwan", "laimax" : [ 3, 6, 4, 5, 2, 6, 5, 7, 3, 4, 2, 6], "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Tajikistan, "name" : "Tajikistan", "laimax" : [ 2, 4, 3, 5, 1, 3, 1, 2, 2, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tanzania_United_Republic_of, "name" : "Tanzania United Republic of", "laimax" : [ 2, 2, 1, 1, 1, 1, 2, 1, 3, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Thailand, "name" : "Thailand", "laimax" : [ 7, 3, 3, 2, 1, 1, 5, 2, 6, 3, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Timor_Leste, "name" : "Timor Leste", "laimax" : [ 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Togo, "name" : "Togo", "laimax" : [ 2, 2, 1, 1, 1, 1, 2, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tokelau, "name" : "Tokelau", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Tonga, "name" : "Tonga", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Trinidad_and_Tobago, "name" : "Trinidad and Tobago", "laimax" : [ 1, 2, 2, 2, 2, 5, 4, 4, 5, 2, 7, 2], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Tunisia, "name" : "Tunisia", "laimax" : [ 1, 6, 5, 5, 1, 1, 1, 1, 7, 6, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Turkey, "name" : "Turkey", "laimax" : [ 2, 6, 7, 2, 7, 4, 1, 7, 4, 4, 3, 1], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Turkmenistan, "name" : "Turkmenistan", "laimax" : [ 3, 4, 2, 5, 7, 7, 1, 2, 2, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Turks_and_Caicos_Islands, "name" : "Turks and Caicos Islands", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Tuvalu, "name" : "Tuvalu", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Uganda, "name" : "Uganda", "laimax" : [ 2, 1, 1, 3, 1, 1, 3, 4, 3, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Ukraine, "name" : "Ukraine", "laimax" : [ 2, 5, 3, 4, 2, 2, 1, 2, 2, 1, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_Arab_Emirates, "name" : "United Arab Emirates", "laimax" : [ 2, 6, 5, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 6, "default_irrig_system" : 3},
  { "id" : United_Kingdom, "name" : "United Kingdom", "laimax" : [ 5, 6, 5, 4, 3, 7, 1, 4, 3, 5, 3, 1], "laimax_tempcer" : 7, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_States_Minor_Outlying_Islands, "name" : "United States Minor Outlying Islands", "laimax" : [ 2, 5, 7, 4, 3, 7, 1, 7, 4, 4, 4, 7], "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : Uruguay, "name" : "Uruguay", "laimax" : [ 1, 4, 3, 2, 3, 5, 4, 2, 3, 2, 7, 7], "laimax_tempcer" : 5, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Uzbekistan, "name" : "Uzbekistan", "laimax" : [ 4, 2, 3, 3, 1, 1, 1, 7, 2, 1, 2, 1], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Vanuatu, "name" : "Vanuatu", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Venezuela, "name" : "Venezuela", "laimax" : [ 1, 4, 3, 2, 2, 5, 3, 3, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 6, "default_irrig_system" : 1},
  { "id" : Vietnam, "name" : "Vietnam", "laimax" : [ 3, 5, 3, 5, 2, 6, 3, 7, 4, 3, 2, 3], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Virgin_Islands, "name" : "Virgin Islands", "laimax" : [ 1, 4, 3, 2, 2, 5, 4, 4, 5, 2, 7, 6], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Wallis_and_Futuna, "name" : "Wallis and Futuna", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 2, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : West_Bank, "name" : "West Bank", "laimax" : [ 4, 6, 5, 5, 3, 6, 1, 7, 7, 1, 2, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Western_Sahara, "name" : "Western Sahara", "laimax" : [ 2, 2, 2, 2, 1, 1, 3, 4, 3, 1, 1, 5], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Western_Samoa, "name" : "Western Samoa", "laimax" : [ 2, 4, 3, 2, 1, 1, 4, 2, 3, 2, 1, 3], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 2},
  { "id" : Yemen, "name" : "Yemen", "laimax" : [ 4, 6, 2, 5, 1, 6, 1, 4, 7, 6, 2, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Zaire_DR_Congo, "name" : "Zaire DR Congo", "laimax" : [ 2, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 6], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Zambia, "name" : "Zambia", "laimax" : [ 7, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 7], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Zimbabwe, "name" : "Zimbabwe", "laimax" : [ 5, 2, 1, 1, 1, 1, 2, 1, 4, 1, 1, 7], "laimax_tempcer" : 6, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Australia, "name" : "Australia", "laimax" : [ 2, 5, 3, 4, 2, 7, 1, 7, 7, 5, 6, 7], "laimax_tempcer" : 4, "laimax_maize" : 5, "default_irrig_system" : 1},
  { "id" : Brazil, "name" : "Brazil", "laimax" : [ 2, 3, 3, 2, 3, 5, 4, 3, 5, 2, 7, 7], "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : Canada, "name" : "Canada", "laimax" : [ 3, 5, 7, 4, 3, 7, 1, 3, 4, 4, 4, 7], "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2},
  { "id" : China, "name" : "China", "laimax" : [ 3, 6, 4, 5, 2, 6, 7, 7, 3, 4, 2, 7], "laimax_tempcer" : 6, "laimax_maize" : 7, "default_irrig_system" : 1},
  { "id" : India, "name" : "India", "laimax" : [ 5, 4, 2, 3, 2, 1, 7, 2, 7, 2, 3, 4], "laimax_tempcer" : 4, "laimax_maize" : 4, "default_irrig_system" : 1},
  { "id" : Russia, "name" : "Russia", "laimax" : [ 2, 4, 4, 6, 2, 3, 1, 2, 2, 1, 2, 1], "laimax_tempcer" : 3, "laimax_maize" : 4, "default_irrig_system" : 2},
  { "id" : United_States, "name" : "United States", "laimax" : [ 2, 5, 7, 4, 2, 7, 1, 7, 4, 4, 4, 7], "laimax_tempcer" : 3, "laimax_maize" : 7, "default_irrig_system" : 2}
],
