/**************************************************************************************/
/**                                                                                \n**/
/**               o  u  t  p  u  t  v  a  r  s  .  j  s                            \n**/
/**                                                                                \n**/
/**  Defines array of output variables for LPJmL 5.1.001                           \n**/
/**  Time step for output can be set via keyword:                                  \n**/
/**  "timstep" : ANNUAL, MONTHLY or DAILY                                          \n**/
/**                                                                                \n**/
/** (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file    \n**/
/** authors, and contributors see AUTHORS file                                     \n**/
/** This file is part of LPJmL and licensed under GNU AGPL Version 3               \n**/
/** or later. See LICENSE file or go to http://www.gnu.org/licenses/               \n**/
/** Contact: https://github.com/PIK-LPJmL/LPJmL                                    \n**/
/**                                                                                \n**/
/**************************************************************************************/

"compress" : 0,          /* compression level (1-9, 0= no compression) */
"missing_value" : -1e32, /* missing value in NetCDF files */

"outputvar" :
[
  /* id           name   timestep       variable(NetCDF) description             unit               scale          offset */
  { "id" : GRID, "name" : "grid", "timestep" : ANNUAL, "var" : "soil", "descr" : "coordinates", "unit" : "degree", "scale" : 1.0, "offset" : 0.0},
  { "id" : FPC, "name" : "fpc", "timestep" : ANNUAL, "var" : "FPC", "descr" : "foliage projected cover", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : NPP, "name": "npp", "timestep" : MONTHLY, "var" : "NPP", "descr" : "monthly NPP", "unit" : "gC/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : GPP, "name": "gpp", "timestep" : MONTHLY, "var" : "GPP", "descr" : "monthly GPP", "unit" : "gC/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : RH, "name": "rh", "timestep" : MONTHLY, "var" : "RH", "descr" : "monthly heterotrophic respiration", "unit" : "gC/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : TRANSP, "name": "transp", "timestep" : MONTHLY, "var" : "transp", "descr" : "monthly transpiration", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : TRANSP_B, "name": "transp_b", "timestep" : MONTHLY, "var" : "transp_b", "descr" : "monthly transpired irrigation water", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : RUNOFF, "name": "runoff", "timestep" : MONTHLY, "var" : "runoff", "descr" :  "monthly runoff", "unit":  "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : DISCHARGE, "name": "discharge",  "timestep" : MONTHLY, "var" : "discharge", "descr" : "monthly discharge", "unit" : "hm3/d", "scale" : 1.0, "offset" : 0.0},
  { "id" : WATERAMOUNT, "name": "wateramount", "timestep" : MONTHLY, "var" : "wateramount", "descr" : "mean monthly water amount", "unit" : "hm3", "scale" : 1.0, "offset" : 0.0},
  { "id" : EVAP, "name": "evap", "timestep" : MONTHLY, "var" : "evap", "descr" : "monthly evaporation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : EVAP_B, "name": "evap_b", "timestep" : MONTHLY, "var" : "evap_b", "descr" : "monthly evaporation of irrigation water", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : INTERC, "name": "interc", "timestep" : MONTHLY, "var" : "interc", "descr" : "monthly interception", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : INTERC_B, "name": "interc_b", "timestep" : MONTHLY, "var" : "interc_b", "descr" : "monthly blue interception", "unit" :  "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC, "name": "swc", "timestep" : MONTHLY, "var" : "SWC", "descr" : "fractional saturation of soil water content", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC1, "name": "swc1", "timestep" : MONTHLY, "var" : "SWC1", "descr" : "fractional saturation of soil water content in layer 1", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC2, "name": "swc2", "timestep" : MONTHLY, "var" : "SWC2", "descr" : "fractional saturation of soil water content in layer 2", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREC, "name": "firec", "timestep" : ANNUAL, "var" : "FireC", "descr" : "fire carbon emission", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREF, "name": "firef", "timestep" : ANNUAL, "var" : "Firef", "descr" : "fire interval", "unit" : "yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : VEGC, "name": "vegc", "timestep" : ANNUAL, "var" : "VegC", "descr" : "vegetation carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILC, "name": "soilc", "timestep" : ANNUAL, "var" : "SoilC", "descr" : "total soil carbon density", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : LITC, "name": "litc", "timestep" : ANNUAL, "var" : "LitC", "descr" : "litter carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : LITFALLC, "name": "litfalc", "timestep" : ANNUAL, "var" : "litfallc", "descr" : "litter fall carbon", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : LITFALLN, "name": "litfaln", "timestep" : ANNUAL, "var" : "litfalln", "descr" : "litter fall nitrogen", "unit" : "gN/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : FLUX_ESTABC, "name": "flux_estabc", "timestep" : ANNUAL, "var" : "estabc", "descr" : "establishment flux", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_NPP, "name": "pft_npp", "timestep" : ANNUAL, "var" : "NPP", "descr" : "PFT-specific NPP", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_GCGP, "name": "pft_gcgp", "timestep" : ANNUAL, "var" : "GCGP", "descr" : "PFT-specific water stress", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : HARVESTC, "name": "harvestc", "timestep" : ANNUAL, "var" : "harvestc", "descr" : "harvested carbon", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : IRRIG, "name": "irrig", "timestep" : MONTHLY, "var" : "irrig", "descr" : "irrigation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SDATE, "name": "sdate", "timestep" : ANNUAL, "var" : "sdate", "descr" : "sowing date", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_HARVESTC, "name": "pft_harvestc", "timestep" : ANNUAL, "var" : "harvestc", "descr" : "harvested carbon", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_RHARVESTC, "name": "pft_rharvestc", "timestep" : ANNUAL, "var" : "rharvestc", "descr" : "harvested residual carbon", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : COUNTRY, "name": "country", "timestep" : ANNUAL, "var" : "country", "descr" : "country code", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : REGION, "name": "region", "timestep" : ANNUAL, "var" : "region", "descr" : "region code", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : MG_VEGC, "name": "mg_vegc", "timestep" : ANNUAL, "var" : "mVegC", "descr" : "managed vegetation carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : MG_SOILC, "name": "mg_soilc", "timestep" : ANNUAL, "var" : "mSoilC", "descr" : "managed soil carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : MG_LITC, "name": "mg_litc", "timestep" : ANNUAL, "var" : "mLitC", "descr" : "managed litter carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : INPUT_LAKE, "name": "input_lake", "timestep" : ANNUAL, "var" : "input_lake", "descr" : "precipitation input to lakes", "unit" : "hm3/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : RETURN_FLOW_B, "name": "return_flow_b", "timestep" : MONTHLY, "var" : "return_flow_b", "descr" : "blue water return flow of runoff", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : EVAP_LAKE, "name": "evap_lake", "timestep" : MONTHLY, "var" : "evap_lake", "descr" : "lake evaporation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : ADISCHARGE, "name": "adischarge", "timestep" : ANNUAL, "var" : "discharge", "descr" : "annual discharge", "unit" : "hm3/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFTFRAC, "name": "cftfrac", "timestep" : ANNUAL, "var" : "CFTfrac", "descr" : "CFT fraction", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_CONSUMP_WATER_G, "name": "cft_consump_water_g", "timestep" : ANNUAL, "var" : "consump_water_g", "descr" : "CFT specific green water consumption", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_CONSUMP_WATER_B, "name": "cft_consump_water_b", "timestep" : ANNUAL, "var" : "consump_water_b", "descr" : "CFT specific blue water consumption", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PROD_TURNOVER, "name": "prod_turnover", "timestep" : ANNUAL, "var" : "prod_turnover", "descr" : "emissions from product turnover", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : DEFOREST_EMIS, "name": "deforest_emis", "timestep" : ANNUAL, "var" : "deforest_emis", "descr" : "deforestation emission", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_AIRRIG, "name": "cft_airrig", "timestep" : ANNUAL, "var" : "irrig", "descr" : "CFT-specific irrigation", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : HDATE, "name": "hdate", "timestep" : ANNUAL, "var" : "hdate", "descr" : "harvesting date", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : GROWING_PERIOD, "name": "growing_period", "timestep" : ANNUAL, "var" : "growing_period", "descr" : "", "unit" : "day", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_PET, "name": "cft_pet", "timestep" : ANNUAL, "var" : "pet", "descr" : "CFT-specific potential evapotranspiration", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_TRANSP, "name": "cft_transp", "timestep" : ANNUAL, "var" : "transp", "descr" : "CFT-specific transpiration", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_TRANSP_B, "name": "cft_transp_b", "timestep" : ANNUAL, "var" : "transp_b", "descr" : "CFT-specific blue transpiration", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_EVAP, "name": "cft_evap", "timestep" : ANNUAL, "var" : "evap", "descr" : "CFT-specific evaporation", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_EVAP_B, "name": "cft_evap_b", "timestep" : ANNUAL, "var" : "evap_b", "descr" : "CFT-specific blue evaporation", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_INTERC, "name": "cft_interc", "timestep" : ANNUAL, "var" : "interc", "descr" : "CFT-specific interception", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_INTERC_B, "name": "cft_interc_b", "timestep" : ANNUAL, "var" : "interc_b", "descr" : "CFT-specific blue interception", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_RETURN_FLOW_B, "name": "cft_return_flow_b", "timestep" : ANNUAL, "var" : "return_flow_b", "descr" : "CFT-specific irrigation return flow", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_NIR, "name": "cft_nir", "timestep" : ANNUAL, "var" : "nir", "descr" : "CFT-specific net irrigation requirement", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_FPAR, "name": "cft_fpar", "timestep" : ANNUAL, "var" : "FPAR", "descr" : "CFT-specific FPAR", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_TEMP, "name": "cft_temp", "timestep" : ANNUAL, "var" : "temp", "descr" : "CFT-specific temperature", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_PREC, "name": "cft_prec", "timestep" : ANNUAL, "var" : "prec", "descr" : "CFT-specific precipitation", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_CONV_LOSS_EVAP, "name": "cft_conv_loss_evap", "timestep" : ANNUAL, "var" : "conv_loss_evap", "descr" : "CFT-specific evaporative conveyance losses", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_CONV_LOSS_DRAIN, "name": "cft_conv_loss_drain", "timestep" : ANNUAL, "var" : "conv_loss_drain", "descr" : "CFT-specific drainage conveyance losses", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_IRRIG_EVENTS, "name": "cft_irrig_events", "timestep" : ANNUAL, "var" : "count", "descr" : "number of days with irrigation events", "unit" : "days", "scale" : 1.0, "offset" : 0.0},
  /* for daily outputs */
  { "id" : D_LAI, "name": "d_lai", "timestep" : DAILY, "var" : "LAI", "descr" : "leaf area index", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PHEN, "name": "d_phen", "timestep" : DAILY, "var" : "Phen", "descr" : "Phenology", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_CLEAF, "name": "d_cleaf", "timestep" : DAILY, "var" : "LeafC", "descr" : "Leaf carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_CROOT, "name": "d_croot", "timestep" : DAILY, "var" : "RootC", "descr" : "Root carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_CSO, "name": "d_cso", "timestep" : DAILY, "var" : "csoC", "descr" : "carbon in storage organs", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_CPOOL, "name": "d_cpool", "timestep" : DAILY, "var" : "PoolC", "descr" : "carbon in additional pool stem", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_WDF, "name": "d_wdf", "timestep" : DAILY, "var" : "WDF", "descr" :  "water deficit fraction", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_GROWINGDAY, "name": "d_growingday", "timestep" : DAILY, "var" : "growingday", "descr" :  "growing days", "unit" : "d", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PVD, "name": "d_pvd", "timestep" : DAILY, "var" : "PVD" , "descr" : "number of vernalization days required", "unit" : "d", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PHU, "name": "d_phu", "timestep" : DAILY, "var" : "PHU" , "descr" : "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_FPHU, "name": "d_fphu", "timestep" : DAILY, "var" : "FPHU" , "descr" : "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_LAIMAXAD, "name": "d_laimaxad", "timestep" : DAILY, "var" : "LAImaxad", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_LAINPPDEF, "name": "d_lainppdeficit", "timestep" : DAILY, "var" : "LAINPPdeficit", "descr" :  "LAI reduction due to insufficient NPP", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_HUSUM, "name": "d_husum", "timestep" : DAILY, "var" : "husum", "descr" :  "sum of heat units", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_VDSUM, "name": "d_vdsum", "timestep" : DAILY, "var" : "vdsum", "descr" :  "sum of vernalization days", "unit" : "d", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_WSCAL, "name": "d_wscal", "timestep" : DAILY, "var" : "wscal", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_NPP, "name": "d_npp", "timestep" : DAILY, "var" : "NPP", "descr" :  "Net primary production", "unit" : "gC/m2/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_GPP, "name": "d_gpp", "timestep" : DAILY, "var" : "GPP", "descr" :  "Gross primary production", "unit" : "gC/m2/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RD, "name": "d_rd", "timestep" : DAILY, "var" : "RD", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RROOT, "name": "d_rroot", "timestep" : DAILY, "var" : "rroot", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RSO, "name": "d_rso", "timestep" : DAILY, "var" : "RSO", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RPOOL, "name": "d_rpool", "timestep" : DAILY, "var" : "RPool", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_GRESP, "name": "d_gresp", "timestep" : DAILY, "var" : "Gresp", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_TRANS, "name": "d_trans", "timestep" : DAILY, "var" : "Trans", "descr" :  "transpiration", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_EVAP, "name": "d_evap", "timestep" : DAILY, "var" : "evap", "descr" :  "evaporation", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PREC, "name": "d_prec", "timestep" : DAILY, "var" : "prec", "descr" :  "precipitation", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PERC, "name": "d_perc", "timestep" : DAILY, "var" : "perc", "descr" :  "", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_IRRIG, "name": "d_irrig", "timestep" : DAILY, "var" : "irrig", "descr" :  "irrigation", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_W0, "name": "d_w0", "timestep" : DAILY, "var" : "w0", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_W1, "name": "d_w1", "timestep" : DAILY, "var" : "w1", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_WEVAP, "name": "d_wevap", "timestep" : DAILY, "var" : "wevap", "descr" :  "", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_HI, "name": "d_hi", "timestep" : DAILY, "var" : "Hi", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_FHIOPT, "name": "d_fhiopt", "timestep" : DAILY, "var" : "Hiopt", "descr" :  "optimum harvest index HI reached at harvest", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_HIMIND, "name": "d_himind", "timestep" : DAILY, "var" : "Himind", "descr" :  "minimum harvest index HI reached at harvest", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_FROOT, "name": "d_froot", "timestep" : DAILY, "var" : "froot", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_TEMP, "name": "d_temp", "timestep" : DAILY, "var" : "temp", "descr" :  "temperature", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_SUN, "name": "d_sun", "timestep" : DAILY, "var" : "cloud", "descr" :  "cloudiness", "unit" : "%", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PAR, "name": "d_par", "timestep" : DAILY, "var" : "PAR", "descr" :  "Photosynthetic Active Radiation", "unit" : "J/m2/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_DAYLENGTH, "name": "d_daylength", "timestep" : DAILY, "var" : "daylength", "descr" :  "day length", "unit" : "h", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_SWE, "name": "d_swe", "timestep" : DAILY, "var" : "SWE", "descr" :  "snow water equivalent", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_DISCHARGE, "name": "d_discharge", "timestep" : DAILY, "var" : "discharge", "descr" :  "discharge", "unit" : "m3/s", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RUNOFF, "name": "d_runoff", "timestep" : DAILY, "var" : "runoff", "descr" :  "runoff", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_RH, "name": "d_rh", "timestep" : DAILY, "var" : "rh", "descr" :  "heterotrophic respiration", "unit" : "gC/m2/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_INTERC, "name": "d_interc", "timestep" : DAILY, "var" : "interc", "descr" :  "interception", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_ASSIM, "name": "d_assim", "timestep" : DAILY, "var" : "assim", "descr" :  "assim", "unit" : "gC/m2/day", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_ROT_MODE, "name": "d_rot_mode", "timestep" : DAILY, "var" : "rot_mode", "descr" :  "rotation mode", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : D_PET, "name": "d_pet", "timestep" : DAILY, "var" : "PET", "descr" :  "potential evapotranspiration", "unit" : "mm/day", "scale" : 1.0, "offset" : 0.0},
  /* further non-daily outputs */
  { "id" : EVAP_RES, "name": "evap_res", "timestep" : MONTHLY, "var" : "evap_res", "descr" :  "evaporation from reservoirs", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : PREC_RES, "name": "prec_res", "timestep" : MONTHLY, "var" : "prec_res", "descr" :  "reservoir precipitation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : NFIRE, "name": "nfire", "timestep" : MONTHLY, "var" : "nfire", "descr" :  "number of fires", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREDI, "name": "firedi", "timestep" : MONTHLY, "var" : "firedi", "descr" :  "fire danger index", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_CO2, "name": "fireemission_co2", "timestep" : MONTHLY, "var" : "co2_emission", "descr" :  "CO2 fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_CO, "name": "fireemission_co", "timestep" : MONTHLY, "var" : "co_emission", "descr" :  "CO fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_CH4, "name": "fireemission_ch4", "timestep" : MONTHLY, "var" : "ch4_emission", "descr" :  "CH4 fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_VOC, "name": "fireemission_voc", "timestep" : MONTHLY, "var" : "voc_emission", "descr" :  "VOC fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_TPM, "name": "fireemission_tpm", "timestep" : MONTHLY, "var" : "tpm_emission", "descr" :  "TPM fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREEMISSION_NOX, "name": "fireemission_nox", "timestep" : MONTHLY, "var" : "nox_emission", "descr" :  "NOX fire emission", "unit" : "g/m2/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : FLUX_FIREWOOD, "name": "flux_firewood", "timestep" : ANNUAL, "var" :  "flux_firewood", "descr" :  "wood fire emissions", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : RHARVEST_BURNTC, "name": "rharvest_burntc", "timestep" : ANNUAL, "var" :  "rharvest_burnt", "descr" :  "residual burnt carbon", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : RHARVEST_BURNT_IN_FIELDC, "name": "rharvest_burntinfieldc", "timestep" : ANNUAL, "var" :  "rharvest_burntinfield", "descr" :  "", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : TEMP_IMAGE, "name": "temp_image", "timestep" : MONTHLY, "var" :  "temp", "descr" :  "temperature received from IMAGE", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : PREC_IMAGE, "name": "prec_image", "timestep" : MONTHLY, "var" :  "prec", "descr" :  "precipitation received from IMAGE", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SUN_IMAGE, "name": "sun_image", "timestep" : MONTHLY, "var" :  "sun", "descr" :  "sunshine received from IMAGE", "unit" : "%", "scale" : 1.0, "offset" : 0.0},
  { "id" : WET_IMAGE, "name": "wet_image", "timestep" : MONTHLY, "var" :  "wet", "descr" :  "wet days received from IMAGE", "unit" : "day", "scale" : 1.0, "offset" : 0.0},
  { "id" : FBURN, "name": "fburn", "timestep" : ANNUAL, "var" :  "fburn", "descr" :  "fraction of deforested wood burnt", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : FTIMBER, "name": "ftimber", "timestep" : ANNUAL, "var" :  "ftimber", "descr" :  "fraction of deforested wood harvested as timber", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : TIMBER_HARVESTC, "name": "timber_harvestc", "timestep" : ANNUAL, "var" :  "timber_harvestc", "descr" :  "carbon harvested as timber", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PRODUCT_POOL_FAST, "name": "product_pool_fast", "timestep" : ANNUAL, "var" :  "product_pool_fast", "descr" :  "carbon in the fast product pool", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : PRODUCT_POOL_SLOW, "name": "product_pool_slow", "timestep" : ANNUAL, "var" :  "product_pool_slow", "descr" :  "carbon in the slow product pool", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : LUC_IMAGE, "name": "luc_image", "timestep" : ANNUAL, "var" :  "luc_image", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : MAXTHAW_DEPTH, "name": "maxthaw_depth", "timestep" : ANNUAL, "var" :  "maxthaw_depth", "descr" :  "maximum thawing depth", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP, "name": "soiltemp", "timestep" : MONTHLY, "var" :  "soiltemp", "descr" :  "soil temperature", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP1, "name": "soiltemp1", "timestep" : MONTHLY, "var" :  "soiltemp1", "descr" :  "soil temperature in layer 1", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP2, "name": "soiltemp2", "timestep" : MONTHLY, "var" :  "soiltemp2", "descr" :  "soil temperature in layer 2", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP3, "name": "soiltemp3", "timestep" : MONTHLY, "var" :  "soiltemp3", "descr" :  "soil temperature in layer 3", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP4, "name": "soiltemp4", "timestep" : MONTHLY, "var" :  "soiltemp4", "descr" :  "soil temperature in layer 4", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP5, "name": "soiltemp5", "timestep" : MONTHLY, "var" :  "soiltemp5", "descr" :  "soil temperature in layer 5", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILTEMP6, "name": "soiltemp6", "timestep" : MONTHLY, "var" :  "soiltemp6", "descr" :  "soil temperature in layer 6", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : RES_STORAGE, "name": "res_storage", "timestep" : MONTHLY, "var" :  "res_storage", "descr" :  "mean reservoir storage", "unit" : "hm3", "scale" : 1.0, "offset" : 0.0},
  { "id" : RES_DEMAND, "name": "res_demand", "timestep" : MONTHLY, "var" :  "res_demand", "descr" :  "reservoir demand", "unit" : "hm3/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : TARGET_RELEASE, "name": "target_release","timestep" : MONTHLY,  "var" :  "target_release", "descr" :  "target release", "unit" : "hm3/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : RES_CAP, "name": "res_cap", "timestep" : MONTHLY, "var" :  "res_cap", "descr" :  "output of reservoir capacity", "unit" : "hm3/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SEASONALITY, "name": "seasonality", "timestep" : ANNUAL, "var" :  "seasonality", "descr" :  "seasonality", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PET, "name": "pet", "timestep" : MONTHLY, "var" :  "PET", "descr" :  "potential evapotranspiration", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : TRAD_BIOFUEL, "name": "trad_biofuel", "timestep" : ANNUAL, "var" :  "trad_biofuels", "descr" :  "carbon emissions from traditional biofuel burnt", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : AFRAC_WD_UNSUST, "name": "afrac_wd_unsust", "timestep" : ANNUAL, "var" :  "frac_wd_unsust", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : WD_UNSUST, "name": "mwd_unsust", "timestep" : MONTHLY, "var" :  "wd_unsust", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : WD_LOCAL, "name": "mwd_local", "timestep" : MONTHLY, "var" :  "wd_local", "descr" :  "local withdrawal", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : WD_NEIGHB, "name": "mwd_neighb", "timestep" : MONTHLY, "var" :  "wd_neighb", "descr" :  "neighbour withdrawal", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : WD_RES, "name": "mwd_res", "timestep" : MONTHLY, "var" :  "wd_res", "descr" :  "reservoir withdrawal", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : WD_RETURN, "name": "mwd_return", "timestep" : MONTHLY, "var" :  "wd_return", "descr" :  "withdrawals returned to river", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : CONV_LOSS_EVAP, "name": "conv_loss_evap", "timestep" : ANNUAL, "var" :  "conv_loss_evap", "descr" :  "evaporative conveyance loss", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CONV_LOSS_DRAIN, "name": "conv_loss_drain", "timestep" : ANNUAL, "var" :  "conv_loss_drain", "descr" :  "drainage conveyance loss", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : STOR_RETURN, "name": "stor_return", "timestep" : MONTHLY, "var" :  "stor_return", "descr" :  "irrig stor return", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : PREC, "name": "prec", "timestep" : MONTHLY, "var" :  "prec", "descr" :  "monthly precipitation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : RAIN, "name": "rain", "timestep" : MONTHLY, "var" :  "rain", "descr" :  "precipitation fallen as rain", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SNOWF, "name": "snowf", "timestep" : MONTHLY, "var" :  "snowfall", "descr" :  "monthly snowfall", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : MELT, "name": "melt", "timestep" : MONTHLY, "var" :  "melt", "descr" :  "monthly snowmelt", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SNOWRUNOFF, "name": "snowrunoff", "timestep" : MONTHLY, "var" :  "snowrunoff", "descr" :  "", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWE, "name": "swe", "timestep" : MONTHLY, "var" :  "SWE", "descr" :  "snow water equivalent", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILC_LAYER, "name": "soilc_layer", "timestep" : ANNUAL, "var" :  "SoilC", "descr" :  "Soil carbon in layer", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : RUNOFF_SURF, "name": "runoff_surf", "timestep" : MONTHLY, "var" :  "runoff_surf", "descr" :  "surface runoff", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : RUNOFF_LAT, "name": "runoff_lat", "timestep" : MONTHLY, "var" :  "runoff_lat", "descr" :  "lateral runoff", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : SEEPAGE, "name": "seepage",  "timestep" : MONTHLY, "var" :  "seepage", "descr" :  "seepage water", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : BURNTAREA, "name": "burntarea", "timestep" : MONTHLY, "var" :  "burntarea", "descr" :  "monthly area burnt", "unit" : "hectare", "scale" : 1.0, "offset" : 0.0},
  { "id" : SOILC_SLOW, "name": "soilc_slow", "timestep" : ANNUAL, "var" :  "soilc_slow", "descr" :  "slow soil carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC3, "name": "swc3", "timestep" : MONTHLY, "var" :  "SWC3", "descr" :  "fractional saturation of soil water content in layer 3", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC4, "name": "swc4", "timestep" : MONTHLY, "var" :  "SWC4", "descr" :  "fractional saturation of soil water content in layer 4", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : SWC5, "name": "swc5", "timestep" : MONTHLY, "var" :  "SWC5", "descr" :  "fractional saturation of soil water content in layer 5", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : ROOTMOIST, "name": "rootmoist", "timestep" : MONTHLY, "var" :  "rootmoist", "descr" :  "root moisture", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_SRAD, "name": "cft_srad", "timestep" : ANNUAL, "var" :  "srad", "descr" :  "CFT-specific shortwave downward radiation", "unit" : "W/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_ABOVEGBMC, "name": "cft_aboveground_biomassc", "timestep" : ANNUAL, "var" :  "aboveground_biomassc", "descr" :  "CFT aboveground biomass", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_ABOVEGBMN, "name": "cft_aboveground_biomassn", "timestep" : ANNUAL, "var" :  "aboveground_biomassn", "descr" :  "CFT aboveground nitrogen", "unit" : "gN/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : GCONS_RF, "name": "gcons_rf", "timestep" : MONTHLY, "var" :  "gcons_rf", "descr" : "monthly green water consumption on rainfed stands ", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : GCONS_IRR, "name": "gcons_irr", "timestep" : MONTHLY, "var" :  "gcons_irr", "descr" :  "monthly green water consumption on irrigated stands ", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : BCONS_IRR, "name": "bcons_irr", "timestep" : MONTHLY, "var" :  "bcons_irr", "descr" :  "monthly green water consumption on irrigated stands ", "unit" : "mm", "scale" : 1.0, "offset" : 0.0},
  { "id" : WATERUSE_HIL, "name": "wateruse_hil", "timestep" : ANNUAL, "var" :  "wateruse_hil", "descr" :  "", "unit" : "l/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : FAPAR, "name": "fapar", "timestep" : MONTHLY, "var" :  "FPAR", "descr" :  "fraction of absorbed PAR", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : ALBEDO, "name": "albedo", "timestep" : MONTHLY, "var" :  "albedo", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PHEN_TMIN, "name": "phen_tmin", "timestep" : MONTHLY, "var" :  "phen_tmin", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PHEN_TMAX, "name": "phen_tmax", "timestep" : MONTHLY, "var" :  "phen_tmax", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PHEN_LIGHT, "name": "phen_light", "timestep" : MONTHLY, "var" :  "phen_light", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : PHEN_WATER, "name": "phen_water", "timestep" : MONTHLY, "var" :  "phen_water", "descr" :  "", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : WSCAL, "name": "wscal", "timestep" : MONTHLY, "var" :  "wscal", "unit" : "water scalar", "descr" :  "", "scale" : 1.0, "offset" : 0.0},
  { "id" : IRRIG_RW, "name": "irrig_rw", "timestep" : MONTHLY, "var" :  "rw_irrig", "descr" :  "supplementary rainwater irrigation", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : UNMET_DEMAND, "name": "unmet_demand","timestep" : MONTHLY,  "var" :  "unmet_demand", "descr" :  "unavailable requested irrigation water", "unit" : "mm/month", "scale" : 1.0, "offset" : 0.0},
  { "id" : HDATE2, "name": "hdate2", "timestep" : ANNUAL, "var" :  "hdate2", "descr" :  "harvesting date 2nd season", "unit" : "DOY", "scale" : 1.0, "offset" : 0.0},
  { "id" : SDATE2, "name": "sdate2", "timestep" : ANNUAL, "var" :  "sdate2", "descr" :  "sowing date 2nd season", "unit" : "DOY", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_HARVESTC2, "name": "pft_harvestc2", "timestep" : ANNUAL, "var" :  "harvestc2", "descr" :  "harvested carbon 2nd season", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : PFT_RHARVESTC2, "name": "pft_rharvestc2", "timestep" : ANNUAL, "var" :  "rharvestc2", "descr" :  "harvested residual carbon 2nd season", "unit" : "gC/m2/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : GROWING_PERIOD2, "name": "growing_period2", "timestep" : ANNUAL, "var" :  "growing_period2", "descr" :  "", "unit" : "day", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_PET2, "name": "cft_pet2", "timestep" : ANNUAL, "var" :  "pet2", "descr" :  "CFT-specific potential evapotranspiration 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_TRANSP2, "name": "cft_transp2", "timestep" : ANNUAL, "var" :  "transp2", "descr" :  "CFT-specific transpiration 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_EVAP2, "name": "cft_evap2", "timestep" : ANNUAL, "var" :  "evap2", "descr" :  "CFT-specific evaporation 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_INTERC2, "name": "cft_interc2", "timestep" : ANNUAL, "var" :  "interc2", "descr" :  "CFT-specific interception 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_NIR2, "name": "cft_nir2", "timestep" : ANNUAL, "var" :  "nir2", "descr" :  "CFT-specific net irrigation requirement 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_TEMP2, "name": "cft_temp2", "timestep" : ANNUAL, "var" :  "temp2", "descr" :  "CFT-specific temperature 2nd season", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_PREC2, "name": "cft_prec2", "timestep" : ANNUAL, "var" :  "prec2", "descr" :  "CFT-specific precipitation 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_SRAD2, "name": "cft_srad2", "timestep" : ANNUAL, "var" :  "srad2", "descr" :  "CFT-specific shortwave downward radiation 2nd season", "unit" : "W/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_ABOVEGBMC2, "name": "cft_abovegbmc2", "timestep" : ANNUAL, "var" :  "aboveground_biomassc2", "descr" :  "CFT aboveground biomass 2nd season", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFTFRAC2, "name": "cftfrac2", "timestep" : ANNUAL, "var" :  "CFTfrac2", "descr" :  "CFT fraction 2nd season", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : CFT_AIRRIG2, "name": "cft_airrig2", "timestep" : ANNUAL, "var" :  "irrig2", "descr" :  "CFT-specific irrigation 2nd season", "unit" : "mm/yr", "scale" : 1.0, "offset" : 0.0},
  { "id" : SYEAR, "name": "syear", "timestep" : ANNUAL, "var" :  "syear", "descr" :  "year of sowing", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : SYEAR2, "name": "syear2", "timestep" : ANNUAL, "var" :  "syear2", "descr" :  "year of sowing 2nd season", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : AGB, "name": "agb", "timestep" : ANNUAL, "var" :  "AGB", "descr" :  "above ground biomass", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : AGB_TREE, "name": "agb_tree", "timestep" : ANNUAL, "var" :  "agb_tree", "descr" :  "above ground tree biomass", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : LAKEVOL, "name": "lakevol", "timestep" : MONTHLY, "var" :  "lakevol", "descr" :  "lake content volume", "unit" : "dm3", "scale" : 1.0, "offset" : 0.0},
  { "id" : LAKETEMP, "name": "laketemp", "timestep" : MONTHLY, "var" :  "laketemp", "descr" :  "lake surface temperature", "unit" : "Celsius", "scale" : 1.0, "offset" : 0.0},
  { "id" : FIREN, "name": "firen", "timestep" : ANNUAL, "var": "FireN", "descr": "fire nitrogen emission", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : FLUX_ESTABN, "name": "flux_estabn", "timestep" : ANNUAL, "var": "estabn", "descr": "establishment flux", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : HARVESTN, "name": "harvestn", "timestep" : ANNUAL, "var": "harvestn", "descr": "harvested nitrogen", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_HARVESTN, "name": "pft_harvestn", "timestep" : ANNUAL, "var": "harvestn", "descr": "harvested nitrogen", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_RHARVESTN, "name": "pft_rharvestn", "timestep" : ANNUAL, "var": "rharvestn", "descr": "harvested residual nitrogen", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NUPTAKE, "name": "d_nuptake", "timestep" : DAILY, "var": "d_nuptake", "descr": "N uptake", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_N2O_DENIT, "name": "d_n2o_denit", "timestep" : DAILY, "var": "n2o_denit", "descr": "N2O fron denit", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_N2O_NIT, "name": "d_n2o_nit", "timestep" : DAILY, "var": "n2o_nit", "descr": "N2O from nit", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_N2_DENIT, "name": "d_n2_denit", "timestep" : DAILY, "var": "n2_denit", "descr": "N2 from denit", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_LEACHING, "name": "d_leaching", "timestep" : DAILY, "var": "leaching", "descr": "N leaching", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_BNF, "name": "d_bnf", "timestep" : DAILY, "var": "bnf", "descr": "biological N fixation", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NLEAF, "name": "d_nleaf", "timestep" : DAILY, "var": "nleaf", "descr": "N leaf", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NROOT, "name": "d_nroot", "timestep" : DAILY, "var": "nroot", "descr": "N root", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NSO, "name": "d_nso", "timestep" : DAILY, "var": "nso", "descr": "N SO", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NPOOL, "name": "d_npool", "timestep" : DAILY, "var": "npool", "descr": "N pool", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NO3, "name": "d_no3", "timestep" : DAILY, "var": "NO3", "descr": "NO3", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NH4, "name": "d_nh4", "timestep" : DAILY, "var": "NH4", "descr": "NH4", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NSOIL_SLOW, "name": "d_nsoil_slow", "timestep" : DAILY, "var": "nsoil_slow", "descr": "interception", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NSOIL_FAST, "name": "d_nsoil_fast", "timestep" : DAILY, "var": "nsoil_fast", "descr": "interception", "unit": "gN/m2/day", "scale": 1.0, "offset" : 0.0},
  { "id" : D_NLIMIT, "name":  "d_nlimit","timestep" : DAILY, "var": "nlimit", "descr": "ratio N-constrained to unconstrained vmax", "unit": "-", "scale":  1.0, "offset" : 0.0},
  { "id" : D_VSCAL, "name":  "d_vscal","timestep" : DAILY, "var": "vscal", "descr": "N-stress scalor", "unit": "-", "scale":  1.0, "offset" : 0.0},

  /* further non-daily outputs */
  { "id" : RHARVEST_BURNTN, "name": "rharvest_burntn", "timestep" : ANNUAL, "var": "rharvest_burntn", "descr": "residual burnt nitrogen", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : RHARVEST_BURNT_IN_FIELDN, "name": "rharvest_burntinfieldn", "timestep" : ANNUAL, "var": "rharvest_burntinfieldn", "descr": "", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : VEGN, "name": "vegn", "timestep" : ANNUAL, "var": "VegN", "descr": "vegetation nitrogen", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILN, "name": "soiln", "timestep" : ANNUAL, "var": "SoilN", "descr": "total soil nitrogen density", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILN_SLOW, "name": "soiln_slow", "timestep" : ANNUAL, "var": "SoilN_slow", "descr": "slow soil nitrogen density", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILN_LAYER, "name": "soiln_layer", "timestep" : ANNUAL, "var": "SoilN", "descr": "soil nitrogen in layer", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : LITN, "name": "litn", "timestep" : ANNUAL, "var": "LitN", "descr": "litter nitrogen", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILNH4, "name": "soilnh4", "timestep" : ANNUAL, "var": "SoilNH4", "descr": "total soil NH4", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILNO3, "name": "soilno3", "timestep" : ANNUAL, "var": "SoilNO3", "descr": "total soil NO3", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NUPTAKE, "name": "pft_nuptake", "timestep" : ANNUAL, "var": "pft_nuptake", "descr": "N uptake per PFT", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : NUPTAKE, "name": "nuptake", "timestep" : MONTHLY, "var": "N_uptake", "descr": "monthly N uptake", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : LEACHING, "name": "leaching", "timestep" : MONTHLY, "var": "N_leaching", "descr": "monthly N leached to groundwater", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : N2O_DENIT, "name": "n2o_denit", "timestep" : MONTHLY, "var": "N2O_denitrification", "descr": "monthly N2O emissions from denitrification", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : N2O_NIT, "name": "n2o_nit", "timestep" : MONTHLY, "var": "N2O_nitrification", "descr": "monthly N2O emissions from nitrification", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : N2_EMIS, "name": "n2_emis", "timestep" : MONTHLY, "var": "N2_emissions", "descr": "monthly N2 emissions", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : BNF, "name": "bnf", "timestep" : MONTHLY, "var": "bnf", "descr": "monthly biological N fixation", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NDEMAND, "name": "pft_ndemand", "timestep" : ANNUAL, "var": "N_demand", "descr": "nitrogen demand per PFT", "unit": "gN/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : N_MINERALIZATION, "name": "n_mineralization", "timestep" : MONTHLY, "var": "N_mineralization", "descr": "N mineralized", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : N_VOLATILIZATION, "name": "n_volatilization", "timestep" : MONTHLY, "var": "N_volatilization", "descr": "N volatilized", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : N_IMMO, "name": "n_immo", "timestep" : MONTHLY, "var": "N_immobilization", "descr": "N immobilized", "unit": "gN/m2/month", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_CLEAF, "name": "pft_cleaf", "timestep" : ANNUAL, "var": "C_leaf_pft", "descr": "C leaf biomass per PFT", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NLEAF, "name": "pft_nleaf", "timestep" : ANNUAL, "var": "N_leaf_pft", "descr": "N leaf biomass per PFT", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_VEGC, "name": "pft_vegc", "timestep" : ANNUAL, "var": "vegC_pft", "descr": "C biomass per PFT", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_VEGN, "name": "pft_vegn", "timestep" : ANNUAL, "var": "vegN_pft", "descr": "N biomass per PFT", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : NEGC_FLUXES, "name": "negc_fluxes", "timestep" : ANNUAL, "var": "neg_carbon_fluxes", "descr": "negative carbon fluxes per cell", "unit": "gC/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : NEGN_FLUXES, "name": "negn_fluxes", "timestep" : ANNUAL, "var": "neg_nitrogen_fluxes", "descr": "negative nitrogen fluxes per cell", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_LAIMAX, "name": "pft_laimax", "timestep" : ANNUAL, "var": "LAImax_pft", "descr": "LAImax of next year per PFT", "unit": "m2/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_CROOT, "name": "pft_croot", "timestep" : ANNUAL, "var": "C_root_pft", "descr": "C root biomass per PFT", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NROOT, "name": "pft_nroot", "timestep" : ANNUAL, "var": "N_root_pft", "descr": "N root biomass per PFT", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_CSAPW, "name": "pft_csapw", "timestep" : ANNUAL, "var": "C_sapwood_pft", "descr": "C sapwood biomass per PFT", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NSAPW, "name": "pft_nsapw", "timestep" : ANNUAL, "var": "N_sapwood_pft", "descr": "N sapwood biomass per PFT", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_CHAWO, "name": "pft_chawo", "timestep" : ANNUAL, "var": "C_heartwood_pft", "descr": "C heartwood biomass per PFT", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NHAWO, "name": "pft_nhawo", "timestep" : ANNUAL, "var": "N_heartwood_pft", "descr": "N heartwood biomass per PFT", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_HARVESTN2, "name": "pft_harvestn2", "timestep" : ANNUAL, "var": "harvestn2", "descr": "harvested nitrogen 2nd season", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : PFT_RHARVESTN2, "name": "pft_rharvestn2", "timestep" : ANNUAL, "var": "rharvestn2", "descr": "harvested residual nitrogen 2nd season", "unit": "gN/m2/yr", "scale": 1.0, "offset" : 0.0},
  { "id" : CFT_ABOVEGBMN2, "name": "cft_abovegbmn2", "timestep" : ANNUAL, "var": "aboveground_biomassn2", "descr": "CFT aboveground biomass N 2nd season", "unit" : "gN/m2","scale": 1.0, "offset" : 0.0},
  { "id" : PFT_NLIMIT, "name": "pft_nlimit", "timestep" : ANNUAL, "var": "nlimit", "descr": "ratio N-constrained to unconstrained vmax", "unit": "-", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILNO3_LAYER, "name": "soilno3_layer", "timestep" : ANNUAL, "var": "SoilNO3", "descr": "soil NO3 nitrogen in layer", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : SOILNH4_LAYER, "name": "soilnh4_layer", "timestep" : ANNUAL, "var": "SoilNH4", "descr": "soil NH4 nitrogen in layer", "unit": "gN/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : MEAN_VEGC_MANGRASS, "name": "mean_vegc_mangrass", "timestep" : ANNUAL, "var": "VegC", "descr": "Mean veg. C of managed grasslands", "unit": "gC/m2", "scale": 1.0, "offset" : 0.0},
  { "id" : VEGC_AVG, "name": "vegc_avg", "timestep" : ANNUAL, "var" : "VegC", "descr" : "average vegetation carbon", "unit" : "gC/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : NV_LAI, "name": "nv_lai", "timestep" : ANNUAL, "var" : "LAI", "descr" : "mean LAI from natural vegetation", "unit" : "m2/m2", "scale" : 1.0, "offset" : 0.0},
  { "id" : FPC_BFT, "name": "fpc_bft", "timestep" : ANNUAL, "var" : "FPC", "descr" : "FPC for Bioenergie-PFTs and managed grassland", "unit" : "", "scale" : 1.0, "offset" : 0.0},
  { "id" : RH_LITTER, "name": "rh_litter", "timestep" : MONTHLY, "var" : "RH_LITTER", "descr" : "monthly heterotrophic respiration from litter pools", "unit" : "gC/m2/month", "scale" : 1.0, "offset" : 0.0}
],
