.TH close_image 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
close_image \- Closes socket connection to IMAGE model
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void close_image(const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function closes communication channel to IMAGE model. Function is only available if LPJmL was compiled with -DIMAGE flag.
The argument of \fBclose_image\fP is:
.TP
.I config
LPJmL configuration data. Must be initialized by \fBinitmpiconfig()\fP or \fBinitconfig()\fP and read by \fBreadconfig()\fP.
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initmpiconfig(3), initconfig(3), open_image(3)
