.TH fcloseoutput 3  "January 09, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
fcloseoutput \- closes LPJmL output files
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void fcloseoutput(Outputfile *\fIoutput\fB,const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function closes output files specified in the LPJmL configuration.
The arguments of \fBfcloseoutput\fP are:
.TP
.I output
Pointer to output data opened by \fBfopenoutput\fP.
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
None
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
fopenoutput(3), isopen(3), readconfig(3) 
