.TH fopenoutput 3  "January 09, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
fopenoutput \- creates LPJmL output files
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Outputfile *fopenoutput(const Cell \fIgrid[]\fB,int \fInout\fB,const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function creates and opens output files specified in the LPJmL configuration.
The arguments of \fBfopenoutput\fP are:
.TP
.I grid
Pointer to LPJmL grid. Must be initialized by \fBnewgrid()\fP.
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.TP
.I nout
Maximum number of output files.
.SH RETURN VALUE
Upon successful completion pointer to allocated output data is returned or NULL in case of failure.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
fcloseoutput(3), readconfig(3), newgrid(3), iterate(3), isopen(3) 
