.TH fprintflux 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
fprintflux, printflux \- Print global carbon and water fluxes
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void fprintflux(FILE *\fIfile\fB,Flux \fIflux\fB,Real cflux_total\fB,const Config *\fIconfig\fB);
void printflux(Flux \fIflux\fB,Real \fIcflux_total\fB,const Config *\fIconfig\fB);

.fi
.SH DESCRIPTION
Function prints global carbon and water fluxes. \fBprintflux()\fP writes output to standard output.
The arguments of \fBfprintflux\fP are:
.TP
.I file
File pointer to output stream.
.TP
.I flux
Global carbon and water fluxes. Must be calculated by \fBflux_sum()\fP.
.TP
.I cflux_total
Total flux of carbon. Must be calculated by \fBflux_sum()\fP.
.TP
.I config
LPJmL configuration data. Must be read by \fBreadconfig()\fP. 
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
flux_sum(3), readconfig(3)
