.TH freeinput 3  "November 14, 2018" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
freeinput \- Closes files and deallocates input data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freeinput(Input \fIinput\fB,Bool \fIisroot\fB);

.fi
.SH DESCRIPTION
Function closes open files and deallocates input data.
The argument of \fBfreeinput\fP is:
.TP
.I input
Pointer to input data.  Must be initialized by \fBinitinput()\fP.
.TP
.I isroot
task is root task.
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initinput(3), freeclimate(3), freelanduse(3), freewateruse(3)
