.TH freeclimate 3  "January 19, 2009" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
freeclimate \- Closes files and deallocates climate data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freeclimate(Climate *\fIclimate\fB);

.fi
.SH DESCRIPTION
Function closes open files and deallocates climate data.
The argument of \fBfreeclimate\fP is:
.TP
.I climate
Pointer to climate data.  Must be initialized by \fBinitclimate()\fP.
.SH RETURN VALUE
None.

.SH AUTHORS

See AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initclimate(3), getclimate(3)
