.TH freelanduse 3  "January 9, 2013" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
freelanduse \- Closes file and deallocates land use data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freelanduse(Landuse \fIlanduse\fB,Bool \fIisroot\fB);

.fi
.SH DESCRIPTION
Function closes open file and deallocates  land use data.
The arguments of \fBfreelanduse\fP are:
.TP
.I landuse
Pointer to land use data.  Must be initialized by \fBinitlanduse()\fP.
.TP
.I isroot
Task is root task.
.SH RETURN VALUE
None.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
initlanduse(3), getlanduse(3)
