.TH freelanduse 3  "version 5.6.20" "LPJmL programmers manual"
.SH NAME
freelanduse \- Closes file and deallocates land use data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freelanduse(Landuse \fIlanduse\fB,const Config *\fIconfig\fB));

.fi
.SH DESCRIPTION
Function closes open file and deallocates  land use data.
The arguments of \fBfreelanduse\fP are:
.TP
.I landuse
Pointer to land use data.  Must be initialized by \fBinitlanduse()\fP.
.TP
.I config
LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
None.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initlanduse(3), getlanduse(3)
