.TH freeinput 3  "February 4, 2009" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
freeinput \- Closes files and deallocates input data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freeinput(Input \fIinput\fB);

.fi
.SH DESCRIPTION
Function closes open files and deallocates input data.
The argument of \fBfreeinput\fP is:
.TP
.I input
Pointer to input data.  Must be initialized by \fBinitinput()\fP.
.SH RETURN VALUE
None.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
initinput(3), freeclimate(3), freelanduse(3), freewateruse(3)
