.TH freeclimate 3  "January 19, 2009" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
freeclimate \- Closes files and deallocates climate data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void freeclimate(Climate *\fIclimate\fB);

.fi
.SH DESCRIPTION
Function closes open files and deallocates climate data.
The argument of \fBfreeclimate\fP is:
.TP
.I climate
Pointer to climate data.  Must be initialized by \fBinitclimate()\fP.
.SH RETURN VALUE
None.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
initclimate(3), getclimate(3)
