.TH fwriterestart 3  "November 14, 2018" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
fwriterestart \- write restart file
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool fwriterestart(const Cell \fIgrid\fB[],
                   int \fInpft\fB,int \fIncft\fB,
                   int \fIyear\fB,
                   const char *\fIfilename\fB,
                   const Config *\fIconfig\fB   
                  );\fP

.fi
.SH DESCRIPTION
Function writes restart file LPJmL.
The arguments of \fBfwriterestart\fP are:
.TP
.I grid
Cell grid array allocated and initialized by \fBnewgrid()\fP.
.TP
.I npft
Number of natural plant functional types.
.TP
.I ncft
Number of crop plant functional types.
.TP
.I year
year restart file is written.
.TP
.I filename
filename of restart file.
.TP
.I config
LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE on error.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
readconfig(3), newgrid(3), iterate(3)
