.TH fwriterestart 3  "January 9, 2013" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
fwriterestart \- write restart file
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool fwriterestart(const Config *\fIconfig\fB   
                   const Cell \fIgrid\fB[],
                   int \fInpft\fB,int \fIncft\fB,
                   int \fIyear\fB     
                  );\fP

.fi
.SH DESCRIPTION
Function writes restart file LPJmL.
The arguments of \fBfwriterestart\fP are:
.TP
.I config
LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.TP
.I grid
Cell grid array allocated and initialized by \fBnewgrid()\fP.
.TP
.I npft
Number of natural plant functional types.
.TP
.I ncft
Number of crop plant functional types.
.TP
.I year
year restart file is written.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE on error.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
readconfig(3), newgrid(3), iterate(3)
