.TH getco2 3  "January 27, 2008" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
getco2 \- get atmospheric CO2 concentration
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Real getco2(const Climate *\fIclimate\fB,int \fI year\fB);\fP

.fi
.SH DESCRIPTION
Function gets atmospheric CO2 concentration  for specified year.
The arguments of \fBgetco2\fP are:
.TP
.I climate
Pointer to climate data. Must be initialized by \fBinitclimate()\fP.
.TP
.I year
year CO2 data is read.
.SH RETURN VALUE
Atmospheric CO2 concentration (ppmv) is returned.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
initclimate(3), freeclimate(3), getclimate(3) 
