.TH getco2 3  "LPJmL programmers manual"
.SH NAME
getco2 \- get atmospheric CO2 concentration
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool getco2(const Climate *\fIclimate\fB,Real *\fIco2\fB,int \fI year\fB);\fP

.fi
.SH DESCRIPTION
Function gets atmospheric CO2 concentration  for specified year.
The arguments of \fBgetco2\fP are:
.TP
.I climate
Pointer to climate data. Must be initialized by \fBinitclimate()\fP.
.TP
.I pco2
pointer to real where atmospheric CO2 concentration (ppmv) is stored.
.TP
.I year
year CO2 data is read.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE in case of error.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initclimate(3), freeclimate(3), getclimate(3) 
