.TH getco2 3  "January 27, 2008" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
getco2 \- get atmospheric CO2 concentration
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Real getco2(const Climate *\fIclimate\fB,int \fI year\fB);\fP

.fi
.SH DESCRIPTION
Function gets atmospheric CO2 concentration  for specified year.
The arguments of \fBgetco2\fP are:
.TP
.I climate
Pointer to climate data. Must be initialized by \fBinitclimate()\fP.
.TP
.I year
year CO2 data is read.
.SH RETURN VALUE
Atmospheric CO2 concentration (ppmv) is returned.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initclimate(3), freeclimate(3), getclimate(3) 
