.TH getpodens 3  "November 15, 2018" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
getpopdens \- Get population density data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Real getpopdens(const Popdens \fIpopdens\fB,int \fIcell\fB);\fP

.fi
.SH DESCRIPTION
Function returns  population density data for specified cell.
The arguments of \fBgetpopdens\fP are:
.TP
.I popdens
Pointer to population density data.  Must be initialized by \fBinitpopdens()\fP and
read by \fBreadpopdens()\fP.
.TP
.I cell
cell index
.SH RETURN VALUE
Population density in capita/km2 is returned.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initpopdens(3), readpopdens(3), freepopdens(3)
