.TH getpopdens 3  "January 9, 2013" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
getpopdens \- Get population density data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool getpopdens(const Popdens \fIpopdens\fB,int \fIyear\fB);\fP

.fi
.SH DESCRIPTION
Function reads population density data for specified year.
The arguments of \fBgetpopdens\fP are:
.TP
.I popdens
Pointer to population density data.  Must be initialized by \fBinitpopdens()\fP.
.TP
.I year
Sets year data is read.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE on error.

.SH AUTHORS

See AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initpopdens(3), freepopdens(3)
