.TH initdrain 3  "January 9, 2013" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
initdrain \- initialize river routing network
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool initdrain(Cell \fIgrid\fB[],Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function initializes river routing network.  
The arguments of \fBinitdrain\fP are:
.TP
.I grid
Cell grid array initialized by \fBnewgrid()\fP.
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE in case of failure.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
newgrid(3), readconfig(3), iterate(3) 
