.TH initlanduse 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
initlanduse \- initialize land use data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Landuse initlanduse(int \fIncft\fB,const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function initializes land use data and opens related files specified in the LPJmL configuration.
The arguments of \fBinitlanduse\fP are:
.TP
.I ncft
Number of crop plant functional types.
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion pointer to allocated land use data is returned and NULL in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
freelanduse(3), getlanduse(3), readconfig(3), iterate(3) 
