.TH initconfig 3  "January 19, 2009" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
initconfig \- Initialize LPJmL configuration for the sequential version
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void initconfig(Config *\fIconfig\fB);

.fi
.SH DESCRIPTION
Function initializes LPJmL configuration.
The argument of \fBinitconfig\fP is:
.TP
.I config
Pointer to LPJmL configuration data. 
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
readconfig(3), initmpiconfig(3), freeconfig(3)
