.TH initclimate 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
initclimate \- initialize climate data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Climate *initclimate(const Cell \fIgrid[]\fB,const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function initializes climate data and opens related files specified in the LPJmL configuration.
The arguments of \fBinitclimate\fP are:
.TP
.I grid
Cell grid array allocated and initialized by \fBnewgrid()\fP.
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion pointer to allocated climate data is returned and NULL in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
getclimate(3), freeclimate(3), readconfig(3), iterate(3) 
