.TH initwateruse 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
initwateruse \- initialize water use data
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Wateruse initwateruse(const Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function initializes water use data and  opens related files specified in the LPJmL configuration.
The argument of \fBinitwateruse\fP is:
.TP
.I config
Pointer to LPJmL configuration data. Must be read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion pointer to allocated water use data is returned and NULL in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
getwateruse(3), freewateruse(3), readconfig(3), iterate(3) 
