.TH initconfig 3  "January 19, 2009" "version 4.0.001" "LPJmL programmers manual"
.SH NAME
initconfig \- Initialize LPJmL configuration for the sequential version
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void initconfig(Config *\fIconfig\fB);

.fi
.SH DESCRIPTION
Function initializes LPJmL configuration.
The argument of \fBinitconfig\fP is:
.TP
.I config
Pointer to LPJmL configuration data. 
.SH RETURN VALUE
None.
.SH AUTHORS
Werner von Bloh (Werner.von.Bloh@pik-potsdam.de),
Sibyll Schaphoff (Sibyll.Schaphoff@pik-potsdam.de),
Stefanie Rost (Jachner) (Stefanie.Rost@pik-potsdam.de),
Marlies Gumpenberger (Marlies.Gumpenberger@pik-potsdam.de),
Tim Beringer (Erbrecht) (Tim.Beringer@pik-potsdam.de),
Christoph Mueller (Christoph.Mueller@pik-potsdam.de)
Jens Heinke (Jens.Heinke@pik-potsdam.de),
Hester Biemans (Hester.Biemans@wur.nl),
Kirsten Thonicke (Kirsten.Thonicke@pik-potsdam.de),
Ursula Heyder (Ursula.Heyder@pik-potsdam.de),

.SH SEE ALSO
readconfig(3), initmpiconfig(3), freeconfig(3)
