.TH open_image 3  "January 20, 2009" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
open_image \- Opens socket connection to IMAGE model
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool open_image(Config *\fIconfig\fB);\fP

.fi
.SH DESCRIPTION
Function opens communication channel to IMAGE model. Function is only available if LPJmL was compiled with -DIMAGE flag.
The argument of \fBopen_image\fP is:
.TP
.I config
Pointer to LPJmL configuration data. Must be initialized by \fBinitmpiconfig()\fP or \fBinitconfig()\fP and read by \fBreadconfig()\fP.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE in case of error.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initmpiconfig(3), initconfig(3), close_image(3)
