.TH pnet_outindex 3  "October 21, 2008" "version 1.0.003" "Pnet programmers manual"
.SH NAME
pnet_outindex \- Get index for output buffer
.SH SYNOPSIS
.nf
\fB#include <mpi.h>
#include "pnet.h"

int pnet_outindex(const Pnet\fP *\fIpnet\fB,int \fIindex\fB);\fP
.fi
.SH DESCRIPTION
Function returns index of node that has to be stored in the output buffer. Function is implemented as a macro.
The arguments of \fBpnet_outindex\fP are:
.TP
.I pnet
Pointer to initialized Pnet struct 
.TP
.I index
Index in output buffer. Must be 0<=index<pnet_outlen(pnet).
.SH RETURN VALUE
Upon successful completion number of connections is returned.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
pnet_init(3), pnet_free(3), pnet_setup(3), pnet_hi(3), pnet_nodes(3)
