.TH pnet_lo 3  "October 21, 2008" "version 1.0.003" "Pnet programmers manual"
.SH NAME
pnet_lo \- Get lower bound for local sublattice
.SH SYNOPSIS
.nf
\fB#include <mpi.h>
#include "pnet.h"

int pnet_lo(const Pnet\fP *\fIpnet\fB);\fP
.fi
.SH DESCRIPTION
Function returns lower bound for local sublattice. Function is implemented as a macro.
The argument of \fBpnet_lo\fP is:
.TP
.I pnet
Pointer to initialized Pnet struct 
.SH RETURN VALUE
Upon successful completion lower bound is returned.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
pnet_init(3), pnet_free(3), pnet_setup(3), pnet_hi(3), pnet_nodes(3)
