.TH printflags 3  "January 26, 2009" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
printflags \- Print LPJmL compilation flags and compiler used
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void printflags(void);

.fi
.SH DESCRIPTION
Function print LPJmL compilation flags, compiler used, endianness and 32/64 bit mode.
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
printlicence(3), readconfig(3), fprintconfig(3), initmpiconfig(3), initconfig(3), freeconfig(3)
