.TH printlicense 3  "November 15, 2018" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
printlicense \- Print LPJmL license file
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void printlicense(void);

.fi
.SH DESCRIPTION
Function prints LPJmL license file on stdout. Environment variable LPJROOT has to be set accordingly to find locaton of license file.
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
readconfig(3), fprintconfig(3), printflags(3), initmpiconfig(3), initconfig(3), freeconfig(3)
