.TH fprintconfig 3  "January 9, 2013" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
fprintconfig, printconfig \- Print LPJmL configuration
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

void fprintconfig(FILE *\fIfile\fB,const Config *\fIconfig\fB);
void printconfig(const Config *\fIconfig\fB);

.fi
.SH DESCRIPTION
Function print LPJmL configuration. \fBprintconfig()\fP writes output to standard output.
The arguments of \fBfprintconfig\fP are:
.TP
.I file
File pointer to output stream.
.TP
.I config
LPJmL configuration data. Must be read by \fBreadconfig()\fP. 
.SH RETURN VALUE
None.
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
readconfig(3), initmpiconfig(3), initconfig(3),freeconfig(3)
