.TH readconfig 3  "December 15, 2008" "version 4.0.002" "LPJmL programmers manual"
.SH NAME
readconfig \- Reads LPJmL configuration
.SH SYNOPSIS
.nf
\fB#include "lpj.h"

Bool readconfig(Config *\fIconfig\fB,const char *\fIfilename\fB,
                Fscanpftparfcn \fIscanfcns\fB[],int \fIntypes\fB,
                int \fInout\fB,int *\fIargc\fB,char ***\fIargv\fB,
                const char *\fIusage\fB);\fP

.fi
.SH DESCRIPTION
Function reads LPJmL configuration.
The arguments of \fBreadconfig\fP are:
.TP
.I config
Pointer to LPJmL configuration data. Must be initialized by \fBinitmpiconfig()\fP or \fBinitconfig()\fP.
.TP
.I filename
Default configuration filename if no filename is given as an argument.
.TP 
.I scanfcns
Vector of scan functions for PFT-specific parameters.
.TP
.I ntypes
Number of plant functional type (PFT) classes.
.TP
.I nout
Maximum number of output files.
.TP
.I argc
Pointer to the number of arguments.
.TP
.I argv
Pointer to argument vector.
.TP
.I usage
Usage string printed in case of error in argument list or NULL.

.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE in case of error.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
initmpiconfig(3), initconfig(3), freeconfig(3)
