.TH writefloat_socket 3  "January 28, 2009" "version 1.0.001" "Socket library manual"
.SH NAME
writefloat_socket \- write floats to socket
.SH SYNOPSIS
.nf
\fB#include "types.h"
#include "channel.h"

Bool writefloat_socket(Socket *\fIsocket\fB,const float *\fIdata\fB,int \fIn\fB);\fP

.fi
.SH DESCRIPTION
Function writes float data to open socket.
The arguments of \fBwritefloat_socket\fP are:
.TP
.I socket
Pointer to socket. Socket must be opened by \fBopen_socket()\fP or \fBconnect_socket()\fP.
.TP
.I data
Float data to write from socket.
.TP
.I n
Number of float values to write.
.SH RETURN VALUE
Upon successful completion FALSE is returned and TRUE on failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
writeint_socket(3), close_socket(3), open_socket(3), connect_socket(3), readint_socket(3)
