/**************************************************************************************/
/**                                                                                \n**/
/**                  c  o  n  f  .  h                                              \n**/
/**                                                                                \n**/
/**     Header for LPJ configuration file                                          \n**/
/**     Must be included by LPJmL configuration file                               \n**/
/**                                                                                \n**/
/** (C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file    \n**/
/** authors, and contributors see AUTHORS file                                     \n**/
/** This file is part of LPJmL and licensed under GNU AGPL Version 3               \n**/
/** or later. See LICENSE file or go to http://www.gnu.org/licenses/               \n**/
/** Contact: https://github.com/PIK-LPJmL/LPJmL                                    \n**/
/**                                                                                \n**/
/**************************************************************************************/

#ifndef CONF_H
#define CONF_H

#define LPJ 0          /* LPJ simulation with natural vegetation only */
#define LPJML 1        /* LPJ simulation with managed land */
#define LPJML_IMAGE 2  /* LPJ simulation with managed land coupled to IMAGE
                          model */
#define LPJML_FMS 3  /* LPJ simulation with managed land coupled to FMS */
#define LANDUSE 1
#define NO_LANDUSE 0
#define CONST_LANDUSE 2
#define ALL_CROPS 3
#define ONLY_CROPS 4
#define NO_FIXED_SDATE 0
#define FIXED_SDATE 1
#define PRESCRIBED_SDATE 2
#define NO_FIXED_SOILPAR 0
#define FIXED_SOILPAR 1
#define PRESCRIBED_SOILPAR 2
#define NO_IRRIGATION 0
#define LIM_IRRIGATION 1
#define POT_IRRIGATION 2
#define ALL_IRRIGATION 3
#ifdef IMAGE
#define GROUNDWATER_IRRIG 1
#define NO_GROUNDWATER_IRRIG 0 // Flag to allow for irrigation from groundwater reservoir (sustainable gw irrigation)
#define AQUIFER_IRRIG 1
#define NO_AQUIFER_IRRIG 0 //Flag to allow for irrigation from aquifers (according to input map for aquifers)
#endif
#define GRASS_HARVEST_OPTIONS 1
#define NO_GRASS_HARVEST_OPTIONS 0
#define GRASS_FIXED_PFT 1
#define NO_GRASS_FIXED_PFT 0
#define LAIMAX_CFT 0
#define LAIMAX_INTERPOLATE 1
#define CONST_LAI_MAX 2
#define LAIMAX_PAR 3
#define NO_RESERVOIR 0
#define RESERVOIR 1
#define NO_DRAINAGE 0
#define DRAINAGE 1
#define NO_EQUILSOIL 0
#define EQUILSOIL 1
#define PERM 1
#define NO_PERM 0
#define NEW_PERC 1
#define OLD_PERC 0
#define NO_NITROGEN 0
#define LIM_NITROGEN 1
#define UNLIM_NITROGEN 2
#define NO_WATERUSE 0
#define WATERUSE 1
#define ALL_WATERUSE 2
#define NO_RWMANAGEMENT 0
#define RWMANAGEMENT 1
#define NO_TILLAGE 0
#define TILLAGE 1
#define READ_TILLAGE 2
#define NO_RESIDUE_REMOVE 0
#define FIXED_RESIDUE_REMOVE 1
#define READ_RESIDUE_DATA 2
#define BMGR_GREEN 0
#define BMGR_BROWN 1
#define RADIATION_LWDOWN 3
#define RADIATION_SWONLY 2
#define RADIATION 1
#define CLOUDINESS 0
#define ALL -1
#define RAW 0
#define CLM 1
#define CLM2 2
#define TXT 3
#define FMS 4
#define META 5
#define CDF 6
#define SOCK 7
#define RESTART 1
#define NO_RESTART 0
#define NO_FIRE 0
#define FIRE 1
#define SPITFIRE 2
#define SPITFIRE_TMAX 3
#define NESTEROV_INDEX 0
#define WVPD_INDEX 1
#define NO_PRESCRIBE_BURNTAREA 0
#define PRESCRIBE_BURNTAREA 1
#define NO_LANDCOVER 0
#define LANDCOVEREST 1
#define LANDCOVERFPC 2
#define OLD_PHENOLOGY 0
#define NEW_PHENOLOGY 1
#define OLD_TRF 0
#define NEW_TRF 1
#define OLD_CROP_PHU 0
#define NEW_CROP_PHU 1
#define PRESCRIBED_CROP_PHU 2
#define NO_POPULATION 0
#define POPULATION 1
#define NO_FIREWOOD 0
#define FIREWOOD 1
#define RANDOM_PREC 1
#define INTERPOLATE_PREC 0
#define NO_FERTILIZER 0
#define FERTILIZER 1
#define AUTO_FERTILIZER 2
#define NOUT 327            /* number of output files */
#define END -1              /* end marker for output files */
#define GRIDBASED 1         /* pft-specific outputs scaled by stand->frac */
#define PFTBASED 0          /* pft-specific outputs not scaled by stand->frac */
#define DAILY_IRRIG 1       /* daily outputs for irrigated crop */
#define DAILY_RAINFED 0     /* daily outputs for rain-fed crop */
#define CONST_PREC 2
#define ANNUAL -2
#define MONTHLY -3
#define DAILY -4
/* output*/
#define GRID 0
#define COUNTRY 1
#define REGION 2
#define GLOBALFLUX 3
#define FPC 4
#define TRANSP 5
#define RUNOFF 6
#define DISCHARGE 7
#define EVAP 8
#define INTERC 9
#define SWC1 10
#define SWC2 11
#define FIREC 12
#define FIREF 13
#define VEGC 14
#define SOILC 15
#define LITC 16
#define FLUX_ESTABC 17
#define PFT_NPP 18
#define PFT_GCGP 19
#define HARVESTC 20
#define IRRIG 21
#define SDATE 22
#define PFT_HARVESTC 23
#define PFT_RHARVESTC 24
#define NPP 25
#define GPP 26
#define MG_VEGC 27
#define MG_SOILC 28
#define MG_LITC 29
#define AGB_TREE 30
#define INPUT_LAKE 31
#define RETURN_FLOW_B 32
#define EVAP_LAKE 33
#define ADISCHARGE 34
#define CFTFRAC 35
#define CFT_CONSUMP_WATER_G 36
#define CFT_CONSUMP_WATER_B 37
#define PROD_TURNOVER 38
#define DEFOREST_EMIS 39
#define NV_LAI 40
#define CFT_AIRRIG 41
#define HDATE 42
#define GROWING_PERIOD 43
#define CFT_PET 44
#define CFT_TRANSP 45
#define CFT_EVAP 46
#define CFT_INTERC 47
#define CFT_NIR 48
#define CFT_TEMP 49
#define CFT_PREC 50
#define WD_AQ 51
#define YDISCHARGE 52
#define TEMP 53
#define SUN 54
#define DAYLENGTH 55
#define EVAP_RES 56
#define PREC_RES 57
#define LITBURNC_WOOD 58
#define WFT_VEGC 59
#define NFIRE 60
#define FIREDI 61
#define FIREEMISSION_CO2 62
#define FAPAR 63
#define FLUX_FIREWOOD 64
#define RHARVEST_BURNTC 65
#define RHARVEST_BURNT_IN_FIELDC 66
#define TEMP_IMAGE 67
#define PREC_IMAGE 68
#define SUN_IMAGE 69
#define WET_IMAGE 70
#define FBURN 71
#define FTIMBER 72
#define TIMBER_HARVESTC 73
#define PRODUCT_POOL_FAST 74
#define PRODUCT_POOL_SLOW 75
#define LUC_IMAGE 76
#define MAXTHAW_DEPTH 77
#define SOILTEMP1 78
#define SOILTEMP2 79
#define SOILTEMP3 80
#define SOILTEMP4 81
#define SOILTEMP5 82
#define SOILTEMP6 83
#define RES_STORAGE 84
#define RES_DEMAND 85
#define TARGET_RELEASE 86
#define RES_CAP 87
#define SEASONALITY 88
#define PET 89
#define TRAD_BIOFUEL 90
#define AFRAC_WD_UNSUST 91
#define WD_UNSUST 92
#define RH_LITTER 93
#define WD_LOCAL 94
#define WD_NEIGHB 95
#define WD_RES 96
#define CONV_LOSS_EVAP 97
#define PREC 98
#define RAIN 99
#define SNOWF 100
#define MELT 101
#define SNOWRUNOFF 102
#define SWE 103
#define SOILC_LAYER 104
#define RUNOFF_SURF 105
#define RUNOFF_LAT 106
#define SEEPAGE 107
#define BURNTAREA 108
#define SOILC_SLOW 109
#define SWC3 110
#define SWC4 111
#define SWC5 112
#define ROOTMOIST 113
#define CFT_SRAD 114
#define CFT_ABOVEGBMC 115
#define GCONS_RF 116
#define GCONS_IRR 117
#define BCONS_IRR 118
#define WATERUSE_HIL 119
#define WATERAMOUNT 120
#define CFT_ABOVEGBMN 121
#define PFT_HARVESTN 122
#define PFT_RHARVESTN 123
#define RHARVEST_BURNTN 124
#define RHARVEST_BURNT_IN_FIELDN 125
#define FLUX_ESTABN 126
#define VEGN 127
#define SOILN 128
#define LITN 129
#define SOILNH4 130
#define SOILNO3 131
#define HARVESTN 132
#define SOILN_LAYER 133
#define SOILN_SLOW 134
#define PFT_NUPTAKE 135
#define NUPTAKE 136
#define LEACHING 137
#define N2O_DENIT 138
#define N2O_NIT 139
#define N2_EMIS 140
#define BNF 141
#define PFT_NDEMAND 142
#define N_MINERALIZATION 143
#define FIREN 144
#define N_IMMO 145
#define PFT_CLEAF 146
#define PFT_NLEAF 147
#define PFT_VEGC 148
#define PFT_VEGN 149
#define IRRIG_RW 150
#define TRANSP_B 151
#define CFT_TRANSP_B 152
#define UNMET_DEMAND 153
#define CFT_FPAR 154
#define EVAP_B 155
#define INTERC_B 156
#define CFT_EVAP_B 157
#define CFT_INTERC_B 158
#define CFT_RETURN_FLOW_B 159
#define CFT_IRRIG_EVENTS 160
#define CFT_CONV_LOSS_EVAP 161
#define CFT_CONV_LOSS_DRAIN 162
#define STOR_RETURN 163
#define CONV_LOSS_DRAIN 164
#define FPC_BFT 165
#define NEGN_FLUXES 166
#define NEGC_FLUXES 167
#define PFT_LAIMAX 168
#define PFT_CROOT 169
#define PFT_NROOT 170
#define PFT_CSAPW 171
#define PFT_NSAPW 172
#define PFT_CHAWO 173
#define PFT_NHAWO 174
#define HDATE2 175
#define SDATE2 176
#define PFT_HARVESTC2 177
#define PFT_RHARVESTC2 178
#define HARVESTC_AGR 179
#define CFT_PET2 180
#define CFT_TRANSP2 181
#define CFT_EVAP2 182
#define CFT_INTERC2 183
#define CFT_NIR2 184
#define CFT_TEMP2 185
#define CFT_PREC2 186
#define CFT_SRAD2 187
#define CFT_ABOVEGBMC2 188
#define CFTFRAC2 189
#define CFT_AIRRIG2 190
#define SYEAR 191
#define SYEAR2 192
#define PFT_HARVESTN2 193
#define PFT_RHARVESTN2 194
#define CFT_ABOVEGBMN2 195
#define N_VOLATILIZATION 196
#define PFT_NLIMIT 197
#define SOILNO3_LAYER 198
#define SOILNH4_LAYER 199
#define WSCAL 200
#define AGB 201
#define LAKEVOL 202
#define LAKETEMP 203
#define FIREEMISSION_CO 204
#define FIREEMISSION_CH4 205
#define FIREEMISSION_VOC 206
#define FIREEMISSION_TPM 207
#define FIREEMISSION_NOX 208
#define SOILTEMP 209
#define SWC 210
#define ALBEDO 211
#define PHEN_TMIN 212
#define PHEN_TMAX 213
#define PHEN_LIGHT 214
#define PHEN_WATER 215
#define VEGC_AVG 216
#define LITFALLC 217
#define LITFALLN 218
#define PFT_LAI 219
#define PFT_MORT 220
#define WATERUSECONS 221
#define WATERUSEDEM 222
#define WD_GW 223
#define LITC_ALL 224
#define LITC_AG 225
#define NPP_AGR 226
#define RH_AGR 227
#define SOILC_AGR 228
#define SOILC_AGR_LAYER 229
#define LITC_AGR 230
#define GROWING_PERIOD2 231
#define DELTA_NORG_SOIL_AGR 232
#define DELTA_NMIN_SOIL_AGR 233
#define DELTA_NVEG_SOIL_AGR 234
#define HUSUM 235
#define HUSUM2 236
#define CFT_SWC 237
#define MEANVEGCMANGRASS 238
#define CFT_RUNOFF 239
#define CFT_RUNOFF2 240
#define CFT_N2O_NIT 241
#define CFT_N2O_NIT2 242
#define PFT_NUPTAKE2 243
#define CFT_N2O_DENIT 244
#define CFT_N2O_DENIT2 245
#define CFT_N2_EMIS 246
#define CFT_N2_EMIS2 247
#define CFT_LEACHING 248
#define CFT_LEACHING2 249
#define CFT_C_EMIS 250
#define CFT_C_EMIS2 251
#define BNF_AGR 252
#define NFERT_AGR 253
#define NMANURE_AGR 254
#define NDEPO_AGR 255
#define NMINERALIZATION_AGR 256
#define NIMMOBILIZATION_AGR 257
#define NUPTAKE_AGR 258
#define NLEACHING_AGR 259
#define N2O_DENIT_AGR 260
#define N2O_NIT_AGR 261
#define NH3_AGR 262
#define N2_AGR 263
#define SEEDN_AGR 264
#define CELLFRAC_AGR 265
#define LITFALLC_AGR 266
#define LITFALLN_AGR 267
#define HARVESTN_AGR 268
#define MGRASS_LITC 269
#define MGRASS_SOILC 270
#define MGRASS_LITN 271
#define MGRASS_SOILN 272
#define CFT_NFERT 273
#define CFT_NFERT2 274
#define FLUX_AUTOFERT 275
#define LITFALLC_WOOD 276
#define LITFALLN_WOOD 277
#define RESPONSE_LAYER_AGR 278
#define RESPONSE_LAYER_NV 279
#define DECAY_WOOD_AGR 280
#define DECAY_WOOD_NV 281
#define DECAY_LEAF_AGR 282
#define DECAY_LEAF_NV 283
#define CSHIFT_FAST_NV 284
#define CSHIFT_SLOW_NV 285
#define LITBURNC 286
#define RH 287
#define PERC 288
#define WHC_NAT 289
#define WHC_GRASS 290
#define WHC_AGR 291
#define KS_NAT 292
#define KS_GRASS 293
#define KS_AGR 294
#define CFT_NHARVEST 295
#define UPTAKEN_MGRASS 296
#define FECESN_MGRASS 297
#define URINEN_MGRASS 298
#define YIELDN_MGRASS 299
#define NH3_MGRASS 300
#define NO3_LEACHING_MGRASS 301
#define N2_MGRASS 302
#define N2O_NIT_MGRASS 303
#define N2O_DENIT_MGRASS 304
#define UPTAKEC_MGRASS 305
#define FECESC_MGRASS 306
#define URINEC_MGRASS 307
#define YIELDC_MGRASS 308
#define RESPC_MGRASS 309
#define METHANEC_MGRASS 310
#define DELTAC_MGRASS 311
#define RA_MGRASS 312
#define RH_MGRASS 313
#define PFT_BNF 314
#define TIMBER_HARVESTN 315
#define PRODUCT_POOL_FAST_N 316
#define PRODUCT_POOL_SLOW_N 317
#define DEFOREST_EMIS_N 318
#define PROD_TURNOVER_N 319
#define FLUX_FIREWOOD_N 320
#define ESTAB_STORAGE_C 321
#define ESTAB_STORAGE_N 322
#define PFT_WATER_DEMAND 323
#define AUTOTROPHIC_RESPIRATION 324
#define NDEPOS 325
#define RHARVESTN 326
#define PFT_GCGP_COUNT 0
#define NDAY_MONTH 1
#define RANDOM_SEED 0

#endif
