.TH addheader 1  "USER COMMANDS"
.SH NAME
addheader \- Add clm header to binary file
.SH SYNOPSIS
.B addheader
[-swap] [-nyear n] [-firstyear n] [-lastyear n] [-ncell n] [-firstcell n] [-nbands n] [-nstep n ] [-timestep n] [-order n] [-version n] [-cellsize s] [-scale s] [-id s] [-type {byte|short|int|float|double}] \fIbinfile\fP \fIclmfile\fP
.SH DESCRIPTION
Program adds clm header to raw  binary file for LPJmL.
.SH OPTIONS
.TP
-swap
Byte order is change in raw binary file
.TP
-nyear n
Set number of years, default is 109
.TP
-firstyear n
Set first year, default is 1901
.TP
-lastyear
Set last year, default is 2009
.TP
-ncell n
Set number of cells, default is 67420
.TP
-firstcell n
Set index of first cell, default is 0
.TP
-nbands n
Set number of bands, default is 12
.TP
-nstep n
Set number of steps, default is 1
.TP
-timestep n
Set number of time steps, default is 1
.TP
-order n
Set order of data, default is 0
.TP
-version n
Set version of clm file, default is 3
.TP
-cellsize s
Set cell size, default is 0.5
.TP
-scale s
Set scaling factor, default is 1
.TP
-id s
Set id string factor, default is LPJCLIM
.TP
-type {byte|short|int|float|double}
Set datatype of clm file. Default is short.
.TP
.I binfile
filename of raw binary file
.TP
.I clmfile
filename of clm data file
.SH EXAMPLE
.TP
Add header to daily climate float data:
.B  addheader
-type float -lastyear 2018 -nbands 365 floatdata.bin file.clm
.PP
.SH EXIT STATUS
.B addheader
return a zero exit status if clm file could be created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
printclm(1), setclm(1), headersize(1), lpjml(1), cru2clm(1), grid2clm(1), cft2clm(1), clm(5)
