.TH asc2clm 1  "April 18, 2016" "version 1.0.002" "USER COMMANDS"
.SH NAME
asc2clm \- convert ARC/Info ASCII files to clm data files for LPJmL
.SH SYNOPSIS
.B asc2clm
[\-h] [\-f] [\-firstyear y] [\-grid file] [\-nbands n] [\-scale s] 
.I ascfile ... clmfile 
[\fIgridfile\fP]
.SH DESCRIPTION
Program converts ARC/Info ASCII (plain text) input data files into LPJ climate data file.
.SH OPTIONS
.TP
\-h
display a short help text
.TP
\-f
force overwrite of existing CLM file
.TP
\-firstyear y 
set first simulation year in CLM file, default is 1901
.TP
\-grid file
write LPJ grid file
.TP
\-nbands n
set number of bands of CLM file, default is 12
.TP
\-header s
set header string of CLM file, default is LPJCLIM
.TP
\-scale s
scale data by a factor
.TP
.I ascfile    
filename(s) of ARC/info ASCII data
.TP
.I clmfile     
filename of clm data file written
.SH EXAMPLES
.TP
Create clm data and grid file from ARC/Info dataset and scale data by 10:
.B asc2clm
-grid grid.clm -scale 10 tmp_1901_*.asc tmp_1901.clm
.PP
.SH EXIT STATUS
.B asc2clm
returns a zero exit status if the clm file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpjml(1), txt2clm(1), cru2clm(1), grid2clm(1), cft2clm(1), catclm(1), clm(5)
