.TH bin2cdf 1  "March 28, 2013" "version 1.0.001" "USER COMMANDS"
.SH NAME
bin2cdf \- convert binary output files into NetCDF files
.SH SYNOPSIS
.B bin2cdf
[\-cellsize size] [\-compress level] [\-descr d] [\-units u] [-global] {-swap] [\-short] [\-nitem n} [\-ispft] [\-firstyear y]
.I varname gridfile binfile netcdffile
.SH DESCRIPTION
Program converts binary output files into NetCDF file.
.SH OPTIONS
.TP
\-cellsize size
set cell size in grid file to size. Default is 0.5 deg.
.TP
\-compress level
compression level for NetCDF4 files
.TP
\-descr d
set long name in NetCDF file
.TP
\-units u
set units in NetCDF file
.TP
\-global
use global grid for NetCDF file
.TP
\-swap 
change byte order in binary file
.TP
\-short 
Data type of output is short, default is float
.TP
\-nitem n
set number of output per year or number of PFTs if -ispft option is set.
.TP
\-ispft
output is PFT specific. 
.TP
\-firstyear
set first year in NetCDF file. Default is 1901. 
.TP
varname
variable name in NetCDF file
.TP
.I gridfile    
filename of grid data file
.TP
.I binfile
filename of binary data file
.TP
.I netcdffile     
filename of NetCDF file created
.SH EXAMPLES
.TP
Create data file for vegetation carbon:
.B bin2cdf
-units gC/m2 -descr "vegetation carbon" vegc output/grid.bin output/vegc.bin vegc.nc
.TP
Convert monthly data:
.B bin2cdf
-units gC/m2/month -descr "Net primary production" -nitem 12 npp output/grid.bin output/mnpp.bin mnpp.nc
.PP
.SH EXIT STATUS
.B bin2cdf
returns a zero exit status if the NetCDF file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
soil2cdf(1), clm2cdf(1), country2cdf(1), lpjml(1)
