.TH cdf2clm 1  "June 26, 2013" "version 1.0.001" "USER COMMANDS"
.SH NAME
cdf2clm \- convert NetCDF files into CLM files
.SH SYNOPSIS
.B cdf2clm
[\-v] [\-scale factor] [\-units u] [\-var name] [\-id string] [\-version v] [\-float] [\-o clmfile] 
gridfile clmfile ...
.SH DESCRIPTION
Program converts NetCDF input data into CLM input data. 
.SH OPTIONS
.TP
\-v
print name of netcdf files
.TP
\-scale factor
scaling factor for CLM files. Default is one
\-units u
set unit to convert from  NetCDF file
.TP
\-var name 
variable name in NetCDF file
.TP
\-id string 
LPJ header string in clm file
.TP
\-version v
version of clm header, default is 3 
.TP
\-float
write float values in clm file, default is short
.TP
.I -o clmfile
filename of CLM data file written. Default is out.clm
.TP
.I gridfile    
filename of grid data file
.TP
.I netcdffile     
filename of NetCDF file(s) converted
.SH EXAMPLES
.TP
Create data file for temperature:
.B cdf2clm
-units celsius -var tas -o temp1901-2010.clm  grid.clm tmp*.nc
.PP
.SH EXIT STATUS
.B cdf2clm
returns a zero exit status if the CLM file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
cdf2coord(1), cdf2bin(1), clm2cdf(1), bin2cdf(1), country2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
