.TH cdf2grid 1  "USER COMMANDS"
.SH NAME
cdf2grid \- convert grid NetCDF file into grid CLM file
.SH SYNOPSIS
.B cdf2grid
[\-var name] [\-{float|double}] [\-scale s] [\-raw] [\-json] netcdffile gridfile
.SH DESCRIPTION
Program convert grid file written in NetCDF format to grid file in raw or CLM format.
.SH OPTIONS
.TP
\-var name
variable name in NetCDF file
\-scale factor
scaling factor for CLM grid file. Default is 0.01
.TP
\-{float|double}
write float or double values in CLM grid file, default is short
.TP
\-raw
Output format is raw without header, default is CLM format
.TP
\-json
An additional JSON metafile with suffix \fI.json\fP is written.
.TP
.I netcdffile
filename of grid NetCDF file
.I gridfile
filename of grid data file written
.SH EXAMPLES
.TP
Create grid binary raw file from grid NetCDF file:
.B cdf2coord
-raw grid.nc grid.clm
.PP
.SH EXIT STATUS
.B cdf2coord
returns a zero exit status if the CLM file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
cdf2coord(1), cdf2clm(1), clm2cdf(1), bin2cdf(1), country2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
