.TH cdf2soil 1  "November 21, 2018" "version 1.0.001" "USER COMMANDS"
.SH NAME
cdf2soil \- convert NetCDF file into binary file
.SH SYNOPSIS
.B cdf2soil [\-var name] [\-float] [\-scale s] [\-soilmap]
netcdffile gridfile soilfile 
.SH DESCRIPTION
Program converts NetCDF input data into soil code or binary input data and writes grid file. 
.SH OPTIONS
.TP
\-var name
variable name in NetCDF file
.TP
\-scale factor
scaling factor for CLM grid file. Default is 0.01
.TP
\-float
write float values in clm file, default is short
.TP
\-soilmap
Use built-in soil map
.TP
.I netcdffile     
filename of NetCDF file converted
.TP
.I gridfile    
filename of grid data file written
.TP
.I soilfile    
filename of soil code data file written
.SH EXAMPLES
.TP
.B cdf2soil
soilcode.nc  -var soil grid.clm soilcode.bin
.PP
.SH EXIT STATUS
.B cdf2soil
returns a zero exit status if the soil code file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
cdf2coord(1), cdf2clm(1), clm2cdf(1), bin2cdf(1), country2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
