.TH cdf2coord 1  "November 21, 2018" "version 1.0.001" "USER COMMANDS"
.SH NAME
cdf2coord \- extract CLM grid from NetCDF file
.SH SYNOPSIS
.B cdf2coord
[\-var name] [\-index i] [\-float] [\-scale s]  netcdffile gridfile
.SH DESCRIPTION
Program extracts grid file in CLM format from  NetCDF input data. All cells with valid input will be put in the grid file. 
.SH OPTIONS
.TP
\-var name 
variable name in NetCDF file
.TP
\-index i
Converting from i-th dataset. Default is first (=0).
.TP
\-scale factor
scaling factor for CLM grid file. Default is 0.01
.TP
\-float
write float values in CLM grid file, default is short
.TP
.I netcdffile     
filename of NetCDF file
.I gridfile    
filename of grid data file written
.SH EXAMPLES
.TP
Create coord file from temperatureo data file:
.B cdf2coord
-var tas -o temp1901-2010.nc  grid.clm
.PP
.SH EXIT STATUS
.B cdf2coord
returns a zero exit status if the CLM file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
clm2bin(), clm2cdf(1), bin2cdf(1), country2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
