.TH cdf2clm 1  "April 23, 2018" "version 1.0.001" "USER COMMANDS"
.SH NAME
cdf2bin \- convert NetCDF files into raw binary data
.SH SYNOPSIS
.B cdf2bin
[\-v] [\-swap] [\-units u] [\-var name] [\-clm] [\-cellsize size [\-o binfile] 
gridfile netcdffile ...
.SH DESCRIPTION
Program converts NetCDF output data into raw binary output data data. 
.SH OPTIONS
.TP
\-v
print name of netcdf files
.TP
\-swap
byte order of grid file has to be swapped
\-units u
units to convert data from NetCDF file
.TP
\-var name 
variable name in NetCDF file
.TP
\-clm
gridfile is in CLM format, raw be default
.TP
\-cellsize size
cell size in grid file, default is 0.5
.TP
\-o binfile
filename of raw binary data file written. Default is out.bin
.TP
.I gridfile    
filename of binaray grid data file consisting of short values
.TP
.I netcdffile     
filename of NetCDF file(s) converted
.SH EXAMPLES
.TP
Create output file for vegetation carbon:
.B cdf2bin
-var vegc -o vegc1901-2010.bin  grid.bin vegc.nc
.PP
.SH EXIT STATUS
.B cdf2bin
returns a zero exit status if the binary file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
bin2cdf(1), country2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
