.TH clm2cdf 1  "USER COMMANDS"
.SH NAME
clm2cdf \- convert CLM files into NetCDF files
.SH SYNOPSIS
.B clm2cdf
[\-h] [\-v] [\-global] [\-longheader] [\-scale factor] [\-cellsize size] [\-byte] [\-int] [\-float] [[\-attr name=value] ...] [\-intnetcdf] [\-metafile] [\-map name] [\-raw] [\-nbands n] [\-landuse] [\-notime] [\-compress level] [\-units u] [\-descr d] [\-missing_value val]
.I [varname gridfile] clmfile netcdffile
.SH DESCRIPTION
Program converts CLM input data into NetCDF input data.
.SH OPTIONS
.TP
\-h,\--help
print help text
.TP
\-v,\--version
print LPJmL version
.TP
\-global
use global grid for NetCDF file
.TP
\-longheader
force version of CLM file to 2
.TP
\-scale factor
scaling factor for CLM version 1 files. Default is one
.TP
\-cellsize size
set cell size of grid file to size
.TP
\-byte
set data type in CLM file to byte, default is short or read from CLM header
.TP
\-int
set data type in CLM file to int, default is short or read from CLM header
.TP
\-float
set data type in CLM file to float, default is short or read from CLM header
.TP
\-attr name=value
set global attribute name in output files to value
.TP
\-intnetcdf
set data type in NetCDF file to int, default is float for short and float datatypes in CLM files
.TP
\-metafile
set the input format to JSON metafile instead of CLM.
.TP
\-map name
name of map in JSON metafile, default is "map"
.TP
\-raw
set the input format to raw instead of CLM
.TP
\-nbands n
set the number of bands to n. This is only active if raw format is set. Default is one
.TP
-landuse
convert land-use input data
.TP
-notime
No time dimension in NetCDF file
.TP
\-compress level
compression level for NetCDF4 files
.TP
\-units u
set units in NetCDF file
.TP
\-descr d
set long name in NetCDF file
.TP
\-missing_value val
set missing value in NetCDF file to val
.TP
varname
variable name in NetCDF file. If not specified variable name is read from metafile
.TP
.I gridfile
filename of grid data file. If not specified grid name is read from metafile
.TP
.I clmfile
filename of CLM data file
.TP
.I netcdffile
filename of NetCDF file created
.SH EXAMPLES
.TP
Create data file for temperature:
.B clm2cdf
-units celsius -descr temperature temp grid.bin tmp.clm tmp.nc
.TP
Create data file for temperature using JSON metafile:
.B clm2cdf
-metafile tmp.clm.json tmp.nc
.PP
.SH EXIT STATUS
.B clm2cdf
returns a zero exit status if the NetCDF file is created.
Non zero is returned in case of failure.

.SH AUTHORS

See AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
bin2cdf(1), country2cdf(1), drainage2cdf(1), reservoir2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
