.TH cmpbin 1  "USER COMMANDS"
.SH NAME
cmpbin \- compares two binary output files
.SH SYNOPSIS
.B cmpbin
[\-metafile] [\-verbose] [\-csv] [\-short] \fIfile1.bin\fP \fIfile2.bin\fP

.SH DESCRIPTION
Program compares two binary output files. The maximum difference and its location, the sum of all absolute differences and the average difference are printed.
.SH OPTIONS
.TP
\-metafile
Output files are JSON metafiles describing the structure of the raw binary file.
.TP
\-verbose
Print values and absolute difference for each different data item.
.TP
\-csv
Print output in comma-separated format.
.TP
\-short
Datatype of binary data is short, default is float. If \-metafile option is set then datatype is read from JSON metafile.
.TP
.I file1.bin file2.bin
Filenames of binary output data files to compare.
.SH EXAMPLE
.TP
Compare two binary files in the current directory:
.B cmpbin
vegc1.bin vegc2.bin
.TP
or
.B cmpbin
-metafile vegc1.bin.json vegc2.bin.json
.PP
.SH EXIT STATUS
.B cmpbin
returns a zero exit status if binary files could be compared.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
bin2cdf(1), cdf2bin(1), lpjml(1)
