.TH cmprestart 1  "USER COMMANDS"
.SH NAME
cmprestart \- Compare two restart files for LPJmL and check for identity
.SH SYNOPSIS
.B cmprestart
[\-q] \fIrestartfile1\fP \fIrestartfile2\fP

.SH DESCRIPTION
The programm checks if all objects of the first file are also contained in the second file and compares their values.
In case of a difference the variable name and the two values are printed.
.SH OPTIONS
.TP
\-q
Print only the tota count of different values.
.TP
.I restartfile1
Name of first restart file.
.TP
.I restartfile2
Name of second restart file to compare.
.SH EXAMPLE
.TP
Compare two restart files:
.B cmprestart
restart1.lpj restart2.lpj
.PP
.SH EXIT STATUS
.B
cmprestart
returns a zero exit status if the two restart file have been compared successfully.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
json2restart(1), restart2yaml(1), lpjprint(1), lpjml(1), lpjcheck(1), lpjfiles(1)
