.TH configure.sh 1  "June 24, 2019" "version 4.0.002" "USER COMMANDS"
.SH NAME
configure.sh \- Configure LPJmL
.SH SYNOPSIS
.B configure.sh
[-h] [-prefix \fIdir\fP] [-debug] [-nompi] [-check] [-Dmacro[=value] ...]
.SH DESCRIPTION
Script configures LPJmL for specific OS and compiler. File \fIMakefile.inc\fP and scripts \fBlpj_paths.sh\fP, \fBlpj_paths.csh\fP are created. After configuration LPJmL program and utilities can be created by invoking

.B make all

.SH OPTIONS
.TP
-h
display a short help text.
.TP
-prefix \fIdir\fP
Set installation directory for LPJmL. Default is current working directory.
.TP
-debug
Set debug flags and disable optimization of compiler. LPJmL has to be rebuilt by invoking \fBmake clean\fP and \fBmake all\fP.
.TP
-check
Set debug flags, enable pointer checking for access out of bounds and disable optimization of compiler. LPJmL has to be rebuilt by invoking \fBmake clean\fP and \fBmake all\fP.
.TP
-nompi
Do not build the MPI version of the code.
.TP
-Dmacro[=value]
Defines macro for compilation
.SH EXAMPLE
.TP
Configure LPJmL with installation directory \fI/data/biosx/lpjml\fP:
.B ./configure.sh
-prefix /data/biosx/lpjml
.PP
Then \fBmake install\fP will install LPJmL in the target directory specified by '-prefix'.
.SH EXIT STATUS
.B configure.sh
returns a zero exit status if LPJmL has been configured successfully.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpj_paths.sh(1), lpj_paths.csh(1), lpjml(1)
