.TH catclm 1  "January 11, 2019" "version 4.0.002" "USER COMMANDS"
.SH NAME
cutclm \- cuts LPJmL climate data files
.SH SYNOPSIS
.B cutclm [\-longheader] [\-end] year
\fIinfile\fP \fIoutfile\fP
.SH DESCRIPTION
Program cuts climate data files in clm format.
.SH OPTIONS
.TP
\-longheader
Long (version 2) header assumed for clm files
.TP
\-end
copy clm data till year, default is copy clm data from year
.TP
year
year to start/end copying
.TP
.I infile
Filename(s) of clm files to be cut
.TP
.I outfile
Filename of new clm file
.SH EXAMPLE
.TP
Create clm data file staring from year 1950:
.B cutclm
1950 temp_1901-2003.bin temp_1950-2003.clm
.PP
.SH EXIT STATUS
.B cutclm
returns a zero exit status if the clm file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpjml(1), catclm(1), txt2clm(1), grid2clm(1), cft2clm(1), clm(5)
