.TH drainage2cdf 1  "USER COMMANDS"
.SH NAME
drainage2cdf \- convert CLM drainage file into NetCDF file
.SH SYNOPSIS
.B drainage2cdf
[\-var name] [\-compress level] [–\netcdf4]
.I soilfile.nc gridfile drainagefile netcdffile
.SH DESCRIPTION
Program converts CLM drainage data into NetCDF input data using the soil code NetCDF file. If drainage CLM file has 2 bands, then the second band is the length of the river and written as variable "riverlen" into the NetCDF file.
.SH OPTIONS
.TP
\-var name
name of soil code variable in the soil code NetCDF file
.TP
\-compress level
compression level for NetCDF4 files
.TP
\-netcdf4
File written is in NetCDF4 format, compress flag is enabled.
.TP
.I gridfile
filename of grid data file
.TP
.I drainagefile
filename of CLM drainage data file
.TP
.I netcdffile
filename of NetCDF file created
.SH EXAMPLES
.TP
Create drainage data:
.B darinage2cdf
-var soilcode soil.nc grid.clm drainage.clm drainage.nc
.PP
.SH EXIT STATUS
.B clm2cdf
returns a zero exit status if the NetCDF file is created.
Non zero is returned in case of failure.

.SH AUTHORS

See AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
bin2cdf(1), country2cdf(1), reservoir2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
