.TH lpj_paths.sh 1  "October 13, 2008" "version 4.0.002" "USER COMMANDS"
.SH NAME
lpj_paths.sh \- Set environmental variables used by LPJmL
.SH SYNOPSIS
 .
.B lpj_paths.sh
.SH DESCRIPTION
Script sets environmental variables used by LPJmL. The root directory is defined and the search path for commands and man pages are extended.  The call of
.TI
  . $LPJROOT/bin/lpj_paths.sh

should be added to the 
.I ~./profile 
 
.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpjml(1), lpj_paths.csh(1)
