.TH lpjcat 1  "October 10, 2008" "version 3.4.018" "USER COMMANDS"
.SH NAME
lpjcat \- Concatenates restart files from distributed LPJmL simulations.
.SH SYNOPSIS
.B lpjcat
[\-o \fIoutfile\fP] \fIfilename\fP ...
.SH DESCRIPTION
Program concatenates restart files from the LPJmL model to one joint restart file. Is used to create a restart file from distributed runs started by the 
.B
lpjdistribute
and
.B lpjdistribute_river
scripts.  Program is obsolete for the MPI version of \fBlpjml\fP.
.SH OPTIONS
.TP
\-o \fIoutfile\fP
sets filename of the concatenated restart file. Default is output to stdout.
.TP
.I filename
name of restart file(s).
.SH EXAMPLE
.TP
Concatenates restart files to the file \fIrestart.lpj\fP:
.B lpjcat
\-o restart.lpj restart_*.lpj
.PP

.SH EXIT STATUS
.B lpjcat 
returns a zero exit status if the restart files have been concatenated.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpjml(1), cat2bsq(1), output_bsq(1)
