.TH lpjprint 1  "February 4, 2009" "version 1.0.018" "USER COMMANDS"
.SH NAME
lpjprint \- Print contents of restart file of LPJmL model runs 
.SH SYNOPSIS
.B lpjprint
[\-h] [\-inpath \fIdir\fP] [\-restartpath \fIdir\fP] [[\-Dmacro[=value]] [\-I\fIdir\fP] ...] [\fIfilename\fP [start [end]]]
.SH DESCRIPTION
Program prints contents of restart file of a LPJmL model run. The LPJmL configuration file is read in in order to find the location and name of the restart file.
.SH OPTIONS
.TP
\-h
display a short help text
.TP
\-inpath \fIdir\fP
set the input directory path. The path is added to the input filenames if they do not contain an absolute path.
.TP
\-restartpath \fIdir\fP
set the restart directory path. The path is added to the restart filename if they do not contain an absolute path.
.TP
\-Dmacro{=value]
define macro for the preprocessor of the configuration file
.TP
\-I\fIdir\fP
define include directory for the preprocessor of the configuration file
.TP
.I filename
name of configuration file, default is \fIlpjml.conf\fP.
.TP
.I start
Index of first grid cell to be printed.
.TP
.I end
Index of last grid cell to be printed.

.SH EXAMPLE
.TP
Print restart file with default configuration file with restart file located in the scratch file system
.B lpjprint
\-restartpath /scratch/02/lpj
.PP
.SH ENVIRONMENT
.TP
LPJCONFIG
default LPJmL configuration filename
.TP
LPJPREP 
defines preprocessor command for LPJmL configuration file, default is \fBcpp -P\fP.
.TP
LPJROOT
defines the root directory for LPJmL. This directory is added to the
include directories of the preprocessor
.TP
LPJINPATH
Path appended to the input filenames. Only done for filenames without absolute path.
.TP
LPJOPTIONS     
runtime options for the preprocessor of LPJmL configuration files
.TP
LPJRESTARTPATH
Path appended to the restart filenames. Only done for filenames without absolute path.

.SH EXIT STATUS
.B
lpjprint
returns a zero exit status if the restart file has been printed.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
lpjml(1), lpjcheck(1), lpjfiles(1), lpjml.conf(5)
