.TH printclm 1  "May 10, 2016" "version 1.0.001" "USER COMMANDS"
.SH NAME
printclm, printheader \- Print contents of clm files for LPJmL                   
.SH SYNOPSIS
.B printclm
[-metafile] [-header] [-data] [-longheader] [-type {byte|short|int|float|double}] [\-nbands n] [\-start s] [\-end e] [\-first f] [\-last l] \fIclmfile\fP ...

.B printheader
\fIclmfile\fP ...
.SH DESCRIPTION
Program prints file header and data stored in clm data files for LPJmL. \fBprintheader\fP is an alias for \fBprintclm\fP printing the file header only.
.SH OPTIONS
.TP
-metafile
File is a metafile describing the structure of the raw binary file
.TP
-header
Print without header
.TP
-data
Print without data
.TP
-longheader
set long header in CLM files.
.TP
-type {byte|short|int|float|double}
Set datatype of clm file. Default is short.
.TP
-nbands n
Set number  of bands to n ignoring value in file header.
.TP
-start s
Start output of data at year s.
.TP
-end e
End output of data at year e.
.TP
-first f
index of first cell for output.
.TP
-last l
index of last cell for output.
.TP
.I clmfile
filename of clm data file(s)
.SH EXAMPLE
.TP
Print headers of all clm files in the current directory:
.B printclm 
-data *.clm
.TP
or
.B printheader 
*.clm
.PP
.SH EXIT STATUS
.B printclm
and
.B printheader
return a zero exit status if clm file could be printed.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
setclm(1), headersize(1), lpjml(1), cru2clm(1), grid2clm(1), cft2clm(1), clm(5)
