.TH regridlpj 1  "October 25, 2018" "version 1.0.002" "USER COMMANDS"
.SH NAME
regridlpj \- regrid CRU input data set for selected countries or specified grid file
.SH SYNOPSIS
.B regridlpj
[\-dir path] 
.I filesuffix  [countrycode ...]
.SH DESCRIPTION
Program regrids CRU input files for selected countries if country codes are provided. If country code is missing grid file grid_filesuffix.clm is used for regridding. Configuration files input_filesuffix.conf and input_filesuffix.js are created in the current directory.
.SH OPTIONS
.TP
\-dir path
set directory for regridded input files
.TP
.I filesuffix
File suffix for regridded input files and configuration file
.TP
.I countrycode
ISO 3166-1 alpha-3 abbreviations for countries or rountry 
codes as numbers defined in
.I include/managepar.h
.SH EXAMPLES
.TP
Create input data files for USA:
.B regridlpj
usa USA
.PP
.TP
Create input file for amazon basin:
.B regridlpj amazon
.PP
grid file grid_amazon.clm in the current directory is used for regridding.
.SH EXIT STATUS
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
getcountry(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5) 
