.TH regridsoil 1  "USER COMMANDS"
.SH NAME
regridsoil \- regrid soil file to new grid
.SH SYNOPSIS
.B regridclm
[\-search] [\-zero] [\-longheader] [\-json]
.I grid_old.clm grid_new.clm soil_old.clm soil_new.clm
.SH DESCRIPTION
Program reads soil file and corresponding grid file to regrid the soil data to a new grid file.
.SH OPTIONS
.TP
\-search
If grid coordinate cannot be found in old grid nearest grid cell is used
.TP
\-zero
If grid coordinate cannot be found in old grid soil code is set to zero
.TP
\-longheader
Version of CLM grid file is set to 2. By default version is read from file header
.TP
\-json
An additional JSON metafile with suffix \fI.json\fP is written.
.TP
.I grid_old.clm
Corresponding grid filename of input data
.TP
.I grid_new.clm
New grid filename data should be regridded to
.TP
.I  soil_old.clm
Filename of soil file that should be regridded
.TP
.I soil_new.clm
Filename of soil file where regridded data is written
.SH EXAMPLES
.TP
Regrid soil file to the grid file of the amazon basin:
.B regridclm
grid.clm grid_amazon.clm soil.bin soil_amazon.bin
.SH EXIT STATUS
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
regridlpj(1), regridclm(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
