.TH soil2cdf 1  "USER COMMANDS"
.SH NAME
soil2cdf \- convert binary files into NetCDF files
.SH SYNOPSIS
.B soil2cdf
[\-global] [\-cellsize size] [\-compress level] [[\-attr name=value] ...] [\-descr d] [\-netcdf4]
.I varname gridfile soilfile netcdffile
.SH DESCRIPTION
Program converts binary input files into NetCDF file.
.SH OPTIONS
.TP
\-global
Use global grid for NetCDF file.
.TP
\-cellsize size
Set cell size in grid file to size.
.TP
\-compress level
Compression level for NetCDF4 files. Valid levels are 0 (no compression) to 9.
.TP
\-attr name=value
Set global attribute name in output files to value.
.TP
\-descr d
Set long name in NetCDF file.
.TP
\-netcdf4
File written is in NetCDF4 format, compress flag is enabled.
.TP
varname
Variable name in NetCDF file.
.TP
.I gridfile
Filename of grid data file.
.TP
.I soilfile
Filename of binary soil data file.
.TP
.I netcdffile
Filename of NetCDF file created.
.SH EXAMPLES
.TP
Create data file for soil:
.B soil2cdf
soilcode grid.bin soil.bin soil.nc
.PP
.SH EXIT STATUS
.B soil2cdf
returns a zero exit status if the NetCDF file is created.
Non zero is returned in case of failure.

.SH AUTHORS

For authors and contributors see AUTHORS file

.SH COPYRIGHT

(C) Potsdam Institute for Climate Impact Research (PIK), see COPYRIGHT file

.SH SEE ALSO
clm2cdf(1), country2cdf(1), bin2cdf(1), regridlpj(1), lpjml(1), txt2clm(1), cru2clm(1), clm(5)
